/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;
import controller.Acesso;
import controller.Usuario;
import controller.Caixa;
import dao.DAOSistema;
import javax.swing.JOptionPane;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import org.hibernate.Session;
import static view.IFrmFinanceiro.btnCaixa_AbrirCaixa;

/**
 *
 * @author Urbanski
 */
public class FrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form FrmPrincipal
     */
    
    /*
        Formularios
    */
    IFrmFinanceiro financeiro;
    IFrmAcademia academia;
    
    /*
        Objetos
    */
    static Usuario usuario = new Usuario();
    private Acesso acesso = new Acesso();
    static Caixa caixa = null;
    static Caixa ultCaixa = new Caixa();
    
    /*
        Formatação de datas
    */
    private static SimpleDateFormat formatoData = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
    private SimpleDateFormat formatoBanco = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
    
    
    public FrmPrincipal(Usuario usuario) {
        
        if(usuario != null){
            initComponents();
            this.usuario = usuario;
            this.acesso = new Acesso(usuario, new Date(System.currentTimeMillis()));
            acesso.iniciaAcesso(acesso);
            lblPrincipal_Usuario.setText(this.usuario.getLogin());
            lblPrincipal_NomeUsuario.setText(this.usuario.getPessoa().getNome());
            lblPrincipal_InicioSessao.setText(formatoData.format(this.acesso.getDataInicio()));
            this.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        }else{
            JOptionPane.showMessageDialog(this, "Não é possivel acessar sistema sem estar logado. Favor, revisar esse procedimento","ATENÇÃO",JOptionPane.ERROR_MESSAGE);
            dispose();
        }
        atualizarInterface();
    }
    
    public static void atualizarInterface(){
        if(FrmPrincipal.caixa != null){
            lblPrincipal_InicioCaixa.setText(formatoData.format(FrmPrincipal.caixa.getDataInicio()));
        }else{
            lblPrincipal_InicioCaixa.setText("CAIXA FECHADO");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        btnFinanceiro = new javax.swing.JButton();
        btnSuporte = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        btnSuporte1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        dskPrincipal = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblPrincipal_Usuario = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblPrincipal_InicioSessao = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblPrincipal_InicioCaixa = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPrincipal_NomeUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciamento GymClub");
        setExtendedState(6);
        setFocusTraversalPolicyProvider(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Menu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        jPanel3.setPreferredSize(new java.awt.Dimension(132, 358));

        btnFinanceiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/005-piggy-bank.png"))); // NOI18N
        btnFinanceiro.setText("Financeiro");
        btnFinanceiro.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnFinanceiro.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                btnFinanceiroComponentMoved(evt);
            }
        });
        btnFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinanceiroActionPerformed(evt);
            }
        });

        btnSuporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/007-call-center-woman-ultrathin-sign.png"))); // NOI18N
        btnSuporte.setText("Suporte");
        btnSuporte.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSuporte.setPreferredSize(new java.awt.Dimension(70, 25));
        btnSuporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuporteActionPerformed(evt);
            }
        });

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/png/004-logout.png"))); // NOI18N
        btnSair.setText("Sair");
        btnSair.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSair.setPreferredSize(new java.awt.Dimension(70, 25));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        btnSuporte1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/png/001-man.png"))); // NOI18N
        btnSuporte1.setText("Controle");
        btnSuporte1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnSuporte1.setPreferredSize(new java.awt.Dimension(70, 25));
        btnSuporte1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuporte1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 3, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSuporte, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnSuporte1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(10, 10, 10))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnFinanceiro, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(btnSuporte, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(btnSuporte1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel4.setPreferredSize(new java.awt.Dimension(722, 495));

        dskPrincipal.setBackground(new java.awt.Color(0, 0, 51));
        dskPrincipal.setToolTipText("");

        javax.swing.GroupLayout dskPrincipalLayout = new javax.swing.GroupLayout(dskPrincipal);
        dskPrincipal.setLayout(dskPrincipalLayout);
        dskPrincipalLayout.setHorizontalGroup(
            dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        dskPrincipalLayout.setVerticalGroup(
            dskPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPrincipal)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dskPrincipal)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Informações do Usuário"));

        jLabel1.setText("Usuário:");

        jLabel2.setText("Inicio Sessão:");

        jLabel3.setText("Caixa Aberto:");

        jLabel4.setText("Nome:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPrincipal_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPrincipal_NomeUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPrincipal_InicioSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPrincipal_InicioCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblPrincipal_NomeUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPrincipal_InicioSessao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPrincipal_Usuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblPrincipal_InicioCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 725, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 434, Short.MAX_VALUE)
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                        .addContainerGap())))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinanceiroActionPerformed
        if(financeiro == null){
            financeiro = new IFrmFinanceiro(usuario);
        }
        if(!financeiro.isVisible()){
            dskPrincipal.add(financeiro);
            financeiro.setLocation(
                   dskPrincipal.getWidth()/2 - financeiro.getWidth()/2,
                   dskPrincipal.getHeight()/2 - financeiro.getHeight()/2);
            financeiro.show();
        }
        
        try{
            financeiro.toFront();
            financeiro.setSelected(true);
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnFinanceiroActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        if(caixa != null){
            JOptionPane.showMessageDialog(this, "Impossivel finalizar o programa pois o caixa encontra-se aberto, favor fechar antes de finalizar a sessão.","ATENÇÃO",JOptionPane.ERROR_MESSAGE);
        }else{
            dispose();
            acesso.setDataFim(new Date(System.currentTimeMillis()));
            acesso.finalizaAcesso(acesso);
            DAOSistema.getSessionFactory().close();
        }
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnFinanceiroComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnFinanceiroComponentMoved

    }//GEN-LAST:event_btnFinanceiroComponentMoved

    private void btnSuporte1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuporte1ActionPerformed
        IFrmPainel iFrmPainel = null;
        
        if(iFrmPainel == null){
            iFrmPainel = new IFrmPainel(usuario,acesso);
        }
        if(!iFrmPainel.isVisible()){
            FrmPrincipal.dskPrincipal.add(iFrmPainel);
            iFrmPainel.setLocation(
                   dskPrincipal.getWidth()/2 - iFrmPainel.getWidth()/2,
                   dskPrincipal.getHeight()/2 - iFrmPainel.getHeight()/2);
            iFrmPainel.show();
        }
        
        try{
            iFrmPainel.setSelected(true);
            iFrmPainel.toFront();
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnSuporte1ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(caixa == null){
            dispose();
            acesso.setDataFim(new Date(System.currentTimeMillis()));
            acesso.finalizaAcesso(acesso);
            DAOSistema.getSessionFactory().close();
        }else{
            JOptionPane.showMessageDialog(this, "Impossivel finalizar o programa pois o caixa encontra-se aberto, favor fechar antes de finalizar a sessão.","ATENÇÃO",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_formWindowClosing

    private void btnSuporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuporteActionPerformed
        IFrmSuporte iFrmSuporte = new IFrmSuporte();
        
        if(!iFrmSuporte.isVisible()){
            FrmPrincipal.dskPrincipal.add(iFrmSuporte);
            iFrmSuporte.setLocation(
                   dskPrincipal.getWidth()/2 - iFrmSuporte.getWidth()/2,
                   dskPrincipal.getHeight()/2 - iFrmSuporte.getHeight()/2);
            iFrmSuporte.show();
        }
        
        try{
            iFrmSuporte.setSelected(true);
            iFrmSuporte.toFront();
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnSuporteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal(null).setVisible(true);
            }
           
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinanceiro;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSuporte;
    private javax.swing.JButton btnSuporte1;
    public static javax.swing.JDesktopPane dskPrincipal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JLabel lblPrincipal_InicioCaixa;
    private static javax.swing.JLabel lblPrincipal_InicioSessao;
    private static javax.swing.JLabel lblPrincipal_NomeUsuario;
    private static javax.swing.JLabel lblPrincipal_Usuario;
    // End of variables declaration//GEN-END:variables
    

}
