/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.DAOSistema;
import controller.Fornecedor;
import controller.Pessoa;
import controller.Cidade;
import controller.Endereco;
import controller.Estado;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import org.hibernate.Query;

import org.hibernate.Session;

/**
 *
 * @author Urbanski
 */
public class IFrmFinanceiro_Fornecedor_Visualizar extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrmFinanceiro_Fornecedor_Visualizar
     */
    
    public static int fornecedorId;
    private IFrmFinanceiro_Fornecedor_Cadastro ifrmFornecedor_Cadastro;
    private Pessoa p = null;
    private Fornecedor f = null;
    private Endereco e = null;
    
    /*
        Passa para o InternalFrame o fornecedorId para que
        seja realizada consultas para interface
    */
    public IFrmFinanceiro_Fornecedor_Visualizar(int fornecedorId) {
        initComponents();
        this.fornecedorId = fornecedorId;
        carregarFornecedor();
    }

    /*
        Recebe o fornecedor localizado pelo seu id e insere
        os dados em seus respectivos campos
    */
    private void carregarFornecedor(){
        f = new Fornecedor();
        f = f.retornaFornecedor(this.fornecedorId);
        txtVisualizarFornecedor_RazaoSocial.setText(f.getRazao());
        txtVisualizarFornecedor_NomeFantasia.setText(f.getPessoa().getNome());
        frmtVisualizarFornecedor_Cnpj.setText(f.getCnpj());
        frmtVisualizarFornecedor_TelFixo.setText(f.getPessoa().getTelFixo());
        frmtVisualizarFornecedor_TelCel.setText(f.getPessoa().getTelCel());
        txtVisualizarFornecedor_Email.setText(f.getPessoa().getEmail());
        txtVisualizarFornecedor_Ramo.setText(f.getRamo());
        carregaEndereco();
    }
    /*
        Recebe o endereco localizado pelo pessoaId e insere
        os dados em seus respectivos campos
    */
    private void carregaEndereco(){
        e = new Endereco();
        e = e.retornaEndereco(f.getPessoa().getPessoaId());
        txtVisualizarFornecedor_Bairro.setText(e.getBairro());
        txtVisualizarFornecedor_Endereco.setText(e.getRua());
        txtVisualizarFornecedor_Bairro1.setText(String.valueOf(e.getNumero()));
        frmtVisualizarFornecedor_Cep.setText(e.getCep());
        txtVisualizarFornecedor_Estado.setText(e.getCidade().getEstado().getNome());
        txtVisualizarFornecedor_Cidade.setText(e.getCidade().getNome());
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        frmtVisualizarFornecedor_Cep = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtVisualizarFornecedor_Email = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtVisualizarFornecedor_Ramo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnVisualizarFornecedor_Alterar = new javax.swing.JButton();
        txtVisualizarFornecedor_RazaoSocial = new javax.swing.JTextField();
        txtVisualizarFornecedor_NomeFantasia = new javax.swing.JTextField();
        btnVisualizarFornecedor_Fechar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtVisualizarFornecedor_Bairro = new javax.swing.JTextField();
        frmtVisualizarFornecedor_Cnpj = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        frmtVisualizarFornecedor_TelFixo = new javax.swing.JFormattedTextField();
        txtVisualizarFornecedor_Endereco = new javax.swing.JTextField();
        frmtVisualizarFornecedor_TelCel = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtVisualizarFornecedor_Estado = new javax.swing.JTextField();
        txtVisualizarFornecedor_Cidade = new javax.swing.JTextField();
        btnVisualizarFornecedor_Excluir = new javax.swing.JButton();
        txtVisualizarFornecedor_Bairro1 = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Visualizar perfil");
        setPreferredSize(new java.awt.Dimension(699, 407));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Perfil do Fornecedor"));
        jPanel1.setToolTipText("");

        jLabel8.setText("CEP");

        frmtVisualizarFornecedor_Cep.setEditable(false);
        try {
            frmtVisualizarFornecedor_Cep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel9.setText("Cidade");

        jLabel10.setText("Estado");

        jLabel11.setText("E-mail");

        txtVisualizarFornecedor_Email.setEditable(false);

        jLabel12.setText("Ramo");

        txtVisualizarFornecedor_Ramo.setEditable(false);

        jLabel1.setText("Razão Social");

        btnVisualizarFornecedor_Alterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/009-shuffle.png"))); // NOI18N
        btnVisualizarFornecedor_Alterar.setText("Alterar");
        btnVisualizarFornecedor_Alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarFornecedor_AlterarActionPerformed(evt);
            }
        });

        txtVisualizarFornecedor_RazaoSocial.setEditable(false);

        txtVisualizarFornecedor_NomeFantasia.setEditable(false);

        btnVisualizarFornecedor_Fechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/002-cancel-1.png"))); // NOI18N
        btnVisualizarFornecedor_Fechar.setText("Fechar");
        btnVisualizarFornecedor_Fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarFornecedor_FecharActionPerformed(evt);
            }
        });

        jLabel2.setText("Nome Fantasia");

        jLabel13.setText("Bairro");

        jLabel3.setText("CNPJ");

        txtVisualizarFornecedor_Bairro.setEditable(false);

        frmtVisualizarFornecedor_Cnpj.setEditable(false);
        try {
            frmtVisualizarFornecedor_Cnpj.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###/####-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("Tel. Fixo");

        jLabel5.setText("Tel. Celular");

        frmtVisualizarFornecedor_TelFixo.setEditable(false);
        try {
            frmtVisualizarFornecedor_TelFixo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txtVisualizarFornecedor_Endereco.setEditable(false);

        frmtVisualizarFornecedor_TelCel.setEditable(false);
        try {
            frmtVisualizarFornecedor_TelCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("Endereço");

        jLabel7.setText("Número");

        txtVisualizarFornecedor_Estado.setEditable(false);

        txtVisualizarFornecedor_Cidade.setEditable(false);

        btnVisualizarFornecedor_Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/004-user.png"))); // NOI18N
        btnVisualizarFornecedor_Excluir.setText("Excluir");
        btnVisualizarFornecedor_Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisualizarFornecedor_ExcluirActionPerformed(evt);
            }
        });

        txtVisualizarFornecedor_Bairro1.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(15, 15, 15)
                        .addComponent(txtVisualizarFornecedor_RazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtVisualizarFornecedor_NomeFantasia))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnVisualizarFornecedor_Alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(127, 127, 127)
                        .addComponent(btnVisualizarFornecedor_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(124, 124, 124)
                        .addComponent(btnVisualizarFornecedor_Fechar, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 4, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(33, 33, 33)
                        .addComponent(frmtVisualizarFornecedor_Cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(frmtVisualizarFornecedor_TelFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(frmtVisualizarFornecedor_TelCel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel13)
                            .addComponent(jLabel11))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtVisualizarFornecedor_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel7)
                                .addGap(18, 18, 18)
                                .addComponent(txtVisualizarFornecedor_Bairro1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtVisualizarFornecedor_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel10))
                                    .addComponent(txtVisualizarFornecedor_Email))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addComponent(txtVisualizarFornecedor_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addComponent(jLabel9)
                                        .addGap(12, 12, 12))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jLabel12)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtVisualizarFornecedor_Ramo)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(frmtVisualizarFornecedor_Cep, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtVisualizarFornecedor_Cidade))))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtVisualizarFornecedor_RazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtVisualizarFornecedor_NomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(frmtVisualizarFornecedor_Cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(frmtVisualizarFornecedor_TelFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frmtVisualizarFornecedor_TelCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(frmtVisualizarFornecedor_Cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtVisualizarFornecedor_Endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(txtVisualizarFornecedor_Bairro1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtVisualizarFornecedor_Bairro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtVisualizarFornecedor_Cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(txtVisualizarFornecedor_Estado, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtVisualizarFornecedor_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(txtVisualizarFornecedor_Ramo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVisualizarFornecedor_Alterar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVisualizarFornecedor_Fechar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVisualizarFornecedor_Excluir, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVisualizarFornecedor_FecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarFornecedor_FecharActionPerformed
        dispose();
        IFrmFinanceiro.atualizaTblFornecedor();
    }//GEN-LAST:event_btnVisualizarFornecedor_FecharActionPerformed

    /*
        Instancia o formulario de Cadastro para ser realizado
        alterações no cadastro do fornecedor.
    */
    private void btnVisualizarFornecedor_AlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarFornecedor_AlterarActionPerformed
        if(ifrmFornecedor_Cadastro == null){
            ifrmFornecedor_Cadastro = new IFrmFinanceiro_Fornecedor_Cadastro(f);
        }
        
        if(!ifrmFornecedor_Cadastro.isVisible()){
            FrmPrincipal.dskPrincipal.add(ifrmFornecedor_Cadastro);
            ifrmFornecedor_Cadastro.show();
        }
        
        try{
            ifrmFornecedor_Cadastro.setEnabled(true);
            ifrmFornecedor_Cadastro.toFront();
            dispose();
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnVisualizarFornecedor_AlterarActionPerformed

    private void btnVisualizarFornecedor_ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisualizarFornecedor_ExcluirActionPerformed
        
        if(JOptionPane.showConfirmDialog(null, "Deseja realmente excluir o fornecedor\n"+f.getPessoa().getNome()+" ?") == JOptionPane.YES_OPTION){
        
            if(f.verificaExistenciaContaFornecedor(f.getFornecedorId())){
                JOptionPane.showMessageDialog(this, "Não é possivel apagar esse fornecedor pois existem contas pagas de serviços prestado por ele.");
            }else{
                p = f.getPessoa();
                f.excluirFornecedor(f);
                e.excluirEndereco(e);
                p.excluirPessoa(p);
                JOptionPane.showMessageDialog(this, "Fornecedor excluido com sucesso.");
                IFrmFinanceiro.atualizaTblFornecedor();
                dispose();
                IFrmFinanceiro.atualizaAllTbl();
            }
        }
    }//GEN-LAST:event_btnVisualizarFornecedor_ExcluirActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVisualizarFornecedor_Alterar;
    private javax.swing.JButton btnVisualizarFornecedor_Excluir;
    private javax.swing.JButton btnVisualizarFornecedor_Fechar;
    private javax.swing.JFormattedTextField frmtVisualizarFornecedor_Cep;
    private javax.swing.JFormattedTextField frmtVisualizarFornecedor_Cnpj;
    private javax.swing.JFormattedTextField frmtVisualizarFornecedor_TelCel;
    private javax.swing.JFormattedTextField frmtVisualizarFornecedor_TelFixo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtVisualizarFornecedor_Bairro;
    private javax.swing.JTextField txtVisualizarFornecedor_Bairro1;
    private javax.swing.JTextField txtVisualizarFornecedor_Cidade;
    private javax.swing.JTextField txtVisualizarFornecedor_Email;
    private javax.swing.JTextField txtVisualizarFornecedor_Endereco;
    private javax.swing.JTextField txtVisualizarFornecedor_Estado;
    private javax.swing.JTextField txtVisualizarFornecedor_NomeFantasia;
    private javax.swing.JTextField txtVisualizarFornecedor_Ramo;
    private javax.swing.JTextField txtVisualizarFornecedor_RazaoSocial;
    // End of variables declaration//GEN-END:variables
}
