/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;
import controller.Movimento;
import controller.Tipomovimento;
import javax.swing.JOptionPane;

import static view.IFrmFinanceiro.carregaTabela;

/**
 *
 * @author Urbanski
 */
public class IFrmCaixa_SaqueDeposito extends javax.swing.JInternalFrame {

    /** Creates new form IFrmCaixa_SaqueDeposito */
    private Tipomovimento tipoMovimento;
    public IFrmCaixa_SaqueDeposito(int opc) {
        if(FrmPrincipal.caixa == null){
            JOptionPane.showMessageDialog(this, "Caixa Fechado, impossivel continuar essa operação.","ATENÇÃO",JOptionPane.ERROR_MESSAGE);
            dispose();
        }else{
            initComponents();
            spnCaixa_SaldoCaixa.setValue(IFrmFinanceiro.spnCaixa_SaldoAtual.getValue());
            if(opc == 1){
                this.setTitle("Saque");
                this.lblCaixa_ValorDepositoSaque.setText("Valor Saque");
                this.btnCaixa_DepositoSaque.setText("Sacar");
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlCaixa_DepositoSaque = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblCaixa_ValorDepositoSaque = new javax.swing.JLabel();
        btnCaixa_DepositoSaque = new javax.swing.JButton();
        btnCaixa_DepositoSaqueCancelar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtCaixa_Descricao = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        spnCaixa_SaldoCaixa = new javax.swing.JSpinner();
        spnCaixa_ValorDepositoSaque = new javax.swing.JSpinner();

        setClosable(true);
        setTitle("Deposito");

        pnlCaixa_DepositoSaque.setBorder(javax.swing.BorderFactory.createTitledBorder("Deposito"));

        jLabel1.setText("Saldo Caixa");

        lblCaixa_ValorDepositoSaque.setText("Valor Deposito");

        btnCaixa_DepositoSaque.setText("Depositar");
        btnCaixa_DepositoSaque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaixa_DepositoSaqueActionPerformed(evt);
            }
        });

        btnCaixa_DepositoSaqueCancelar.setText("Fechar");
        btnCaixa_DepositoSaqueCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaixa_DepositoSaqueCancelarActionPerformed(evt);
            }
        });

        jLabel2.setText("Descrição");

        txtCaixa_Descricao.setColumns(20);
        txtCaixa_Descricao.setRows(5);
        jScrollPane1.setViewportView(txtCaixa_Descricao);

        jLabel3.setText("R$");

        jLabel4.setText("R$");

        spnCaixa_SaldoCaixa.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));
        spnCaixa_SaldoCaixa.setEnabled(false);

        spnCaixa_ValorDepositoSaque.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));

        javax.swing.GroupLayout pnlCaixa_DepositoSaqueLayout = new javax.swing.GroupLayout(pnlCaixa_DepositoSaque);
        pnlCaixa_DepositoSaque.setLayout(pnlCaixa_DepositoSaqueLayout);
        pnlCaixa_DepositoSaqueLayout.setHorizontalGroup(
            pnlCaixa_DepositoSaqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCaixa_DepositoSaqueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCaixa_DepositoSaqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnCaixa_DepositoSaque)
                    .addComponent(jLabel1)
                    .addComponent(lblCaixa_ValorDepositoSaque)
                    .addGroup(pnlCaixa_DepositoSaqueLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(spnCaixa_ValorDepositoSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCaixa_DepositoSaqueLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(spnCaixa_SaldoCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlCaixa_DepositoSaqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCaixa_DepositoSaqueLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(pnlCaixa_DepositoSaqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlCaixa_DepositoSaqueLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE)))
                    .addGroup(pnlCaixa_DepositoSaqueLayout.createSequentialGroup()
                        .addComponent(btnCaixa_DepositoSaqueCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(10, 10, 10))
        );
        pnlCaixa_DepositoSaqueLayout.setVerticalGroup(
            pnlCaixa_DepositoSaqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCaixa_DepositoSaqueLayout.createSequentialGroup()
                .addGroup(pnlCaixa_DepositoSaqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCaixa_DepositoSaqueLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10)
                        .addGroup(pnlCaixa_DepositoSaqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(spnCaixa_SaldoCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCaixa_ValorDepositoSaque)
                        .addGap(7, 7, 7)
                        .addGroup(pnlCaixa_DepositoSaqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(spnCaixa_ValorDepositoSaque, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlCaixa_DepositoSaqueLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(28, 28, 28)
                .addGroup(pnlCaixa_DepositoSaqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCaixa_DepositoSaque, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCaixa_DepositoSaqueCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlCaixa_DepositoSaque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pnlCaixa_DepositoSaque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCaixa_DepositoSaqueCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixa_DepositoSaqueCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCaixa_DepositoSaqueCancelarActionPerformed

    private void btnCaixa_DepositoSaqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixa_DepositoSaqueActionPerformed
        if(btnCaixa_DepositoSaque.getText().equals("Depositar")){
            Movimento movimento = new Movimento(FrmPrincipal.caixa, tipoMovimento = new Tipomovimento().retornaTipoMovimento(2), txtCaixa_Descricao.getText(), Float.valueOf(spnCaixa_ValorDepositoSaque.getValue().toString()));
            movimento.cadastraMovimento(movimento);
            IFrmFinanceiro.totalEntrada += Float.valueOf(spnCaixa_ValorDepositoSaque.getValue().toString());
        }else{
            Movimento movimento = new Movimento(FrmPrincipal.caixa, tipoMovimento = new Tipomovimento().retornaTipoMovimento(1), txtCaixa_Descricao.getText(), Float.valueOf(spnCaixa_ValorDepositoSaque.getValue().toString()));
            movimento.cadastraMovimento(movimento);
            IFrmFinanceiro.totalSaida += Float.valueOf(spnCaixa_ValorDepositoSaque.getValue().toString());
        }
        IFrmFinanceiro.atualizaCaixa();
        carregaTabela(null, -1, 5);

    }//GEN-LAST:event_btnCaixa_DepositoSaqueActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaixa_DepositoSaque;
    private javax.swing.JButton btnCaixa_DepositoSaqueCancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblCaixa_ValorDepositoSaque;
    private javax.swing.JPanel pnlCaixa_DepositoSaque;
    private javax.swing.JSpinner spnCaixa_SaldoCaixa;
    private javax.swing.JSpinner spnCaixa_ValorDepositoSaque;
    private javax.swing.JTextArea txtCaixa_Descricao;
    // End of variables declaration//GEN-END:variables

}
