/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Caixa;
import controller.Movimento;
import controller.Transacao;
import controller.Usuario;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.BorderFactory;
import javax.swing.JOptionPane;

/**
 *
 * @author Urbanski
 */
public class IFrmCaixa_AbrirFechar extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrmCaixa_AbrirFechar
     */
    private SimpleDateFormat data = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
    
    public void abrirCaixa(){
        float saldoAnterior = Float.valueOf(spnCaixa_AbrirCaixa_SaldoAnterior.getValue().toString());
        float adicionarRetirar = Float.valueOf(spnCaixa_AbrirCaixa_Adicionar.getValue().toString());
        
        if(FrmPrincipal.caixa == null){
            FrmPrincipal.caixa = new Caixa(FrmPrincipal.usuario,(saldoAnterior+adicionarRetirar));
            FrmPrincipal.caixa.abrirCaixa(FrmPrincipal.caixa);
            FrmPrincipal.caixa = FrmPrincipal.caixa.retornaCaixa(FrmPrincipal.caixa.getCaixaId());
            IFrmFinanceiro.saldoInicial = FrmPrincipal.caixa.getSaldoInicial();
            IFrmFinanceiro.atualizaCaixa();
            FrmPrincipal.atualizarInterface();
            dispose();
            IFrmFinanceiro.btnCaixa_AbrirCaixa.setText("Fechar Caixa");
            
        }else{
            
            if(IFrmFinanceiro.saldoAtual < Float.valueOf(spnCaixa_AbrirCaixa_Adicionar.getValue().toString())){
                JOptionPane.showMessageDialog(this, "Valor de retirada invalido. Saldo do caixa não pode ficar negativo.","ATENÇÃO",JOptionPane.ERROR_MESSAGE);
            }else{
                FrmPrincipal.caixa.setSaldoFinal(saldoAnterior-adicionarRetirar);
                FrmPrincipal.caixa.setDataFim(new Date(System.currentTimeMillis()));
                FrmPrincipal.caixa.fecharCaixa(FrmPrincipal.caixa);
                JOptionPane.showMessageDialog(this, "Caixa "+data.format(FrmPrincipal.caixa.getDataFim())+" Fechado. ","SUCESSO",JOptionPane.INFORMATION_MESSAGE);
                IFrmFinanceiro.zerarCaixa();
                dispose();
                FrmPrincipal.lblPrincipal_InicioCaixa.setText("CAIXA FECHADO");
                IFrmFinanceiro.btnCaixa_AbrirCaixa.setText("Abrir Caixa");
                FrmPrincipal.caixa = null;
                IFrmFinanceiro.dtmCaixa = null;
            }
            
        }
    }

    public IFrmCaixa_AbrirFechar() {
        initComponents();
        if(FrmPrincipal.caixa != null){
            this.setTitle("Fechar Caixa");
            this.jPanel1.setBorder(BorderFactory.createTitledBorder("Fechar Caixa"));
            this.btnCaixa_AbrirCaixa_AbriCaixa.setText("Fechar");
            this.lblCaixa_AbrirCaixa_SaldoAnteriorInicial.setText("Saldo Final");
            this.lblCaixa_AbrirCaixa_AdicionarSaldoRetirar.setText("Retirar");
            spnCaixa_AbrirCaixa_SaldoAnterior.setValue(IFrmFinanceiro.saldoAtual);
        }else if(FrmPrincipal.caixa == null){
            Caixa caixaTemp = new Caixa().retornaUltimoCaixa();
            spnCaixa_AbrirCaixa_SaldoAnterior.setValue(caixaTemp.getSaldoFinal());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblCaixa_AbrirCaixa_SaldoAnteriorInicial = new javax.swing.JLabel();
        lblCaixa_AbrirCaixa_AdicionarSaldoRetirar = new javax.swing.JLabel();
        btnCaixa_AbrirCaixa_AbriCaixa = new javax.swing.JButton();
        btnCaixa_AbrirCaixa_Fechar = new javax.swing.JButton();
        spnCaixa_AbrirCaixa_SaldoAnterior = new javax.swing.JSpinner();
        spnCaixa_AbrirCaixa_Adicionar = new javax.swing.JSpinner();

        setTitle("Abri Caixa");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Abrir Caixa"));

        lblCaixa_AbrirCaixa_SaldoAnteriorInicial.setText("Saldo Anterior");

        lblCaixa_AbrirCaixa_AdicionarSaldoRetirar.setText("Adicionar Saldo");

        btnCaixa_AbrirCaixa_AbriCaixa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/calc.png"))); // NOI18N
        btnCaixa_AbrirCaixa_AbriCaixa.setText("Abrir");
        btnCaixa_AbrirCaixa_AbriCaixa.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnCaixa_AbrirCaixa_AbriCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaixa_AbrirCaixa_AbriCaixaActionPerformed(evt);
            }
        });

        btnCaixa_AbrirCaixa_Fechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/png/005-exit.png"))); // NOI18N
        btnCaixa_AbrirCaixa_Fechar.setText("Fechar");
        btnCaixa_AbrirCaixa_Fechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCaixa_AbrirCaixa_FecharActionPerformed(evt);
            }
        });

        spnCaixa_AbrirCaixa_SaldoAnterior.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));
        spnCaixa_AbrirCaixa_SaldoAnterior.setEnabled(false);

        spnCaixa_AbrirCaixa_Adicionar.setModel(new javax.swing.SpinnerNumberModel(0.0f, null, null, 1.0f));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(btnCaixa_AbrirCaixa_AbriCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCaixa_AbrirCaixa_Fechar, javax.swing.GroupLayout.DEFAULT_SIZE, 108, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblCaixa_AbrirCaixa_AdicionarSaldoRetirar)
                    .addComponent(lblCaixa_AbrirCaixa_SaldoAnteriorInicial))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(spnCaixa_AbrirCaixa_SaldoAnterior, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                    .addComponent(spnCaixa_AbrirCaixa_Adicionar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCaixa_AbrirCaixa_SaldoAnteriorInicial)
                    .addComponent(spnCaixa_AbrirCaixa_SaldoAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCaixa_AbrirCaixa_AdicionarSaldoRetirar)
                    .addComponent(spnCaixa_AbrirCaixa_Adicionar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCaixa_AbrirCaixa_AbriCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCaixa_AbrirCaixa_Fechar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCaixa_AbrirCaixa_AbriCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixa_AbrirCaixa_AbriCaixaActionPerformed

        if(JOptionPane.showConfirmDialog(this, "Deseja realmente "+(FrmPrincipal.caixa == null ? "ABRIR" :"FECHAR")+" o caixa?","ATENÇÂO",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                abrirCaixa();
        }
        
    }//GEN-LAST:event_btnCaixa_AbrirCaixa_AbriCaixaActionPerformed

    private void btnCaixa_AbrirCaixa_FecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCaixa_AbrirCaixa_FecharActionPerformed
        dispose();
    }//GEN-LAST:event_btnCaixa_AbrirCaixa_FecharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCaixa_AbrirCaixa_AbriCaixa;
    private javax.swing.JButton btnCaixa_AbrirCaixa_Fechar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCaixa_AbrirCaixa_AdicionarSaldoRetirar;
    private javax.swing.JLabel lblCaixa_AbrirCaixa_SaldoAnteriorInicial;
    private javax.swing.JSpinner spnCaixa_AbrirCaixa_Adicionar;
    private javax.swing.JSpinner spnCaixa_AbrirCaixa_SaldoAnterior;
    // End of variables declaration//GEN-END:variables
}
