/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
import controller.Usuario;
import javax.swing.JOptionPane;

/**
 *
 * @author Urbanski
 */
public class IFrmPainel_TrocarSenha extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrmPainel_VisualizarPerfil
     */
    Usuario usuario = new Usuario();
    public IFrmPainel_TrocarSenha(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPainel_AlterarSenha = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pswPainel_AlterarSenha_SenhaAtual = new javax.swing.JPasswordField();
        pswPainel_AlterarSenha_NovaSenha = new javax.swing.JPasswordField();
        pswPainel_AlterarSenha_ConfirmaSenha = new javax.swing.JPasswordField();
        btnPainel_AlterarSenha_AlterarSenha = new javax.swing.JButton();
        btnPainel_AlterarSenha_Cancelar = new javax.swing.JButton();

        setTitle("Alterar Senha");

        pnlPainel_AlterarSenha.setBorder(javax.swing.BorderFactory.createTitledBorder("Alteração de Senha"));

        jLabel1.setText("Senha Atual");

        jLabel2.setText("Nova Senha");

        jLabel3.setText("Confirma Senha");

        javax.swing.GroupLayout pnlPainel_AlterarSenhaLayout = new javax.swing.GroupLayout(pnlPainel_AlterarSenha);
        pnlPainel_AlterarSenha.setLayout(pnlPainel_AlterarSenhaLayout);
        pnlPainel_AlterarSenhaLayout.setHorizontalGroup(
            pnlPainel_AlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPainel_AlterarSenhaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPainel_AlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(20, 20, 20)
                .addGroup(pnlPainel_AlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pswPainel_AlterarSenha_SenhaAtual, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                    .addComponent(pswPainel_AlterarSenha_NovaSenha)
                    .addComponent(pswPainel_AlterarSenha_ConfirmaSenha))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnlPainel_AlterarSenhaLayout.setVerticalGroup(
            pnlPainel_AlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPainel_AlterarSenhaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPainel_AlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pswPainel_AlterarSenha_SenhaAtual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlPainel_AlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pswPainel_AlterarSenha_NovaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(pnlPainel_AlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pswPainel_AlterarSenha_ConfirmaSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20))
        );

        btnPainel_AlterarSenha_AlterarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/008-pencil-1.png"))); // NOI18N
        btnPainel_AlterarSenha_AlterarSenha.setText("Alterar");
        btnPainel_AlterarSenha_AlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPainel_AlterarSenha_AlterarSenhaActionPerformed(evt);
            }
        });

        btnPainel_AlterarSenha_Cancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/002-cancel-1.png"))); // NOI18N
        btnPainel_AlterarSenha_Cancelar.setText("Cancelar");
        btnPainel_AlterarSenha_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPainel_AlterarSenha_CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlPainel_AlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPainel_AlterarSenha_AlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPainel_AlterarSenha_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(pnlPainel_AlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPainel_AlterarSenha_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPainel_AlterarSenha_AlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPainel_AlterarSenha_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPainel_AlterarSenha_CancelarActionPerformed
        this.usuario = null;
        dispose();
    }//GEN-LAST:event_btnPainel_AlterarSenha_CancelarActionPerformed

    private void btnPainel_AlterarSenha_AlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPainel_AlterarSenha_AlterarSenhaActionPerformed

        if(usuario.getSenha().equals(pswPainel_AlterarSenha_SenhaAtual.getText())){
            if(pswPainel_AlterarSenha_NovaSenha.getText().equals(pswPainel_AlterarSenha_ConfirmaSenha.getText()) && !pswPainel_AlterarSenha_NovaSenha.getText().equals("")){
                usuario.setSenha(pswPainel_AlterarSenha_NovaSenha.getText());
                if(usuario.alterarSenha(usuario)){
                    JOptionPane.showMessageDialog(this, "Senha alterada com sucesso!","SUCESSO",JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                }
            }else{
                JOptionPane.showMessageDialog(this, "Senhas não correspondem ou campos estão vazios.","ATENÇÃO",JOptionPane.ERROR_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(this, "Senha informada não corresponde com a atual.");
        }
    }//GEN-LAST:event_btnPainel_AlterarSenha_AlterarSenhaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPainel_AlterarSenha_AlterarSenha;
    private javax.swing.JButton btnPainel_AlterarSenha_Cancelar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel pnlPainel_AlterarSenha;
    private javax.swing.JPasswordField pswPainel_AlterarSenha_ConfirmaSenha;
    private javax.swing.JPasswordField pswPainel_AlterarSenha_NovaSenha;
    private javax.swing.JPasswordField pswPainel_AlterarSenha_SenhaAtual;
    // End of variables declaration//GEN-END:variables
}
