/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.util.Iterator;

import controller.Chamado;
import controller.Resposta;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static view.FrmPrincipal.dskPrincipal;
/**
 *
 * @author Urbanski
 */
public class IFrmSuporte_VisualizarChamado extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrmSuporte_VisualizarChamado
     */
    private int id;
    private static Chamado chamado = new Chamado();
    private static Resposta resposta = new Resposta();
    private static Iterator i = null;
    private static  DefaultTableModel dtmChamado = null;
    private SimpleDateFormat dataExibicao = new SimpleDateFormat("ddMMYYYY HHssmm");
    
    public void populaCamposChamado(){
        txtSuporte_VisualizarChamado_Solicitante.setText("FALTA INTEGRAÇÃO");
        txtSuporte_VisualizarChamado_Responsavel.setText(chamado.getUsuario().getPessoa().getNome());
        txtSuporte_VisualizarChamado_Situacao.setText(chamado.getSituacao().getStatus());
        txtSuporte_VisualizarChamado_Assunto.setText(chamado.getAssunto());
        frmtSuporte_VisualizarChamado_DataCriacao.setText(dataExibicao.format(chamado.getDataCriacao()));
    }
    
    public static void popularTabelaChamado(){
        dtmChamado = (DefaultTableModel)tblSuporte_VisualizarChamado_Chamado.getModel();
        dtmChamado.setNumRows(0);
        i = resposta.retornaIteratorResposta(chamado.getChamadoId());
       
        Resposta r;
        while(i.hasNext()){
            r = (Resposta)i.next();
            dtmChamado.addRow(r.getRespostas());
        }
        
    }
    
    public IFrmSuporte_VisualizarChamado(int chamadoId) {
        initComponents();
        chamado = chamado.retornaChamado(chamadoId);
        populaCamposChamado();
        popularTabelaChamado();
        if(chamado.getSituacao().getSituacaoId() == 8){
            btnSuporte_VisualizarChamado_Finalizar.setVisible(false);
            btnSuporte_VisualizarChamado_Responder.setVisible(false);
            lblSuporte_VisualizarChamado_DataFinalizacao.setVisible(true);
            frmtSuporte_VisualizarChamado_DataFinalizacao.setVisible(true);
            frmtSuporte_VisualizarChamado_DataFinalizacao.setText(dataExibicao.format(chamado.getDataFim()));
        }else{
            lblSuporte_VisualizarChamado_DataFinalizacao.setVisible(false);
            frmtSuporte_VisualizarChamado_DataFinalizacao.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSuporte_VisualizarChamado_Solicitante = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSuporte_VisualizarChamado_Situacao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtSuporte_VisualizarChamado_Responsavel = new javax.swing.JTextField();
        frmtSuporte_VisualizarChamado_DataCriacao = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSuporte_VisualizarChamado_Assunto = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSuporte_VisualizarChamado_Chamado = new javax.swing.JTable();
        btnSuporte_VisualizarChamado_Responder = new javax.swing.JButton();
        btnSuporte_VisualizarChamado_VisualizarResposta = new javax.swing.JButton();
        btnSuporte_VisualizarChamado_Finalizar = new javax.swing.JButton();
        lblSuporte_VisualizarChamado_DataFinalizacao = new javax.swing.JLabel();
        frmtSuporte_VisualizarChamado_DataFinalizacao = new javax.swing.JFormattedTextField();

        setClosable(true);
        setTitle("Visualizar Chamado");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Informações do Chamado"));

        jLabel1.setText("Solicitante");

        txtSuporte_VisualizarChamado_Solicitante.setEditable(false);

        jLabel2.setText("Situação");

        txtSuporte_VisualizarChamado_Situacao.setEditable(false);

        jLabel3.setText("Responsavel");

        txtSuporte_VisualizarChamado_Responsavel.setEditable(false);

        frmtSuporte_VisualizarChamado_DataCriacao.setEditable(false);
        try {
            frmtSuporte_VisualizarChamado_DataCriacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/#### ##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("Aberto");

        jLabel5.setText("Assunto");

        txtSuporte_VisualizarChamado_Assunto.setEditable(false);

        tblSuporte_VisualizarChamado_Chamado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "REMETENTE", "MENSAGEM", "DATA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblSuporte_VisualizarChamado_Chamado);
        if (tblSuporte_VisualizarChamado_Chamado.getColumnModel().getColumnCount() > 0) {
            tblSuporte_VisualizarChamado_Chamado.getColumnModel().getColumn(0).setResizable(false);
            tblSuporte_VisualizarChamado_Chamado.getColumnModel().getColumn(0).setPreferredWidth(10);
            tblSuporte_VisualizarChamado_Chamado.getColumnModel().getColumn(3).setResizable(false);
            tblSuporte_VisualizarChamado_Chamado.getColumnModel().getColumn(3).setPreferredWidth(20);
        }

        btnSuporte_VisualizarChamado_Responder.setText("Responder");
        btnSuporte_VisualizarChamado_Responder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuporte_VisualizarChamado_ResponderActionPerformed(evt);
            }
        });

        btnSuporte_VisualizarChamado_VisualizarResposta.setText("Visualizar Resposta");
        btnSuporte_VisualizarChamado_VisualizarResposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuporte_VisualizarChamado_VisualizarRespostaActionPerformed(evt);
            }
        });

        btnSuporte_VisualizarChamado_Finalizar.setText("Finalizar Chamado");
        btnSuporte_VisualizarChamado_Finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuporte_VisualizarChamado_FinalizarActionPerformed(evt);
            }
        });

        lblSuporte_VisualizarChamado_DataFinalizacao.setText("Finalizado");

        frmtSuporte_VisualizarChamado_DataFinalizacao.setEditable(false);
        try {
            frmtSuporte_VisualizarChamado_DataFinalizacao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/#### ##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(txtSuporte_VisualizarChamado_Assunto))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txtSuporte_VisualizarChamado_Solicitante, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtSuporte_VisualizarChamado_Situacao)
                                    .addComponent(frmtSuporte_VisualizarChamado_DataCriacao, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblSuporte_VisualizarChamado_DataFinalizacao)
                                        .addGap(18, 18, 18)
                                        .addComponent(frmtSuporte_VisualizarChamado_DataFinalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtSuporte_VisualizarChamado_Responsavel, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSuporte_VisualizarChamado_Responder, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(113, 113, 113)
                        .addComponent(btnSuporte_VisualizarChamado_Finalizar)
                        .addGap(98, 98, 98)
                        .addComponent(btnSuporte_VisualizarChamado_VisualizarResposta)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSuporte_VisualizarChamado_Solicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSuporte_VisualizarChamado_Situacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtSuporte_VisualizarChamado_Responsavel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(frmtSuporte_VisualizarChamado_DataCriacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(frmtSuporte_VisualizarChamado_DataFinalizacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSuporte_VisualizarChamado_DataFinalizacao))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtSuporte_VisualizarChamado_Assunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSuporte_VisualizarChamado_Responder, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuporte_VisualizarChamado_Finalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuporte_VisualizarChamado_VisualizarResposta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuporte_VisualizarChamado_VisualizarRespostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuporte_VisualizarChamado_VisualizarRespostaActionPerformed
        int linha = tblSuporte_VisualizarChamado_Chamado.getSelectedRow();
        if(linha >= 0){
            id = Integer.valueOf(tblSuporte_VisualizarChamado_Chamado.getValueAt(linha, 0).toString());
            IFrmSuporte_VisualizarChamado_VisualizarResposta iFrmSuporte_VisualizarResposta = new IFrmSuporte_VisualizarChamado_VisualizarResposta(id);
            
            if(!iFrmSuporte_VisualizarResposta.isVisible()){
                FrmPrincipal.dskPrincipal.add(iFrmSuporte_VisualizarResposta);
                iFrmSuporte_VisualizarResposta.setLocation(
                   dskPrincipal.getWidth()/2 - iFrmSuporte_VisualizarResposta.getWidth()/2,
                   dskPrincipal.getHeight()/2 - iFrmSuporte_VisualizarResposta.getHeight()/2);
                iFrmSuporte_VisualizarResposta.show();
            }
            
            try{
                iFrmSuporte_VisualizarResposta.setSelected(true);
                iFrmSuporte_VisualizarResposta.toFront();
            }catch(Exception ex){
                ex.printStackTrace();
            }
        }else{
            JOptionPane.showMessageDialog(this, "Selecione uma resposta para vizualização", "ATENÇÃO", JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnSuporte_VisualizarChamado_VisualizarRespostaActionPerformed

    private void btnSuporte_VisualizarChamado_ResponderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuporte_VisualizarChamado_ResponderActionPerformed
        IFrmSuporte_VisualizarChamado_Responder iFrmSuporte_VisualizarChamado_Responder = new IFrmSuporte_VisualizarChamado_Responder(chamado.getChamadoId());
        
        if(!iFrmSuporte_VisualizarChamado_Responder.isVisible()){
            FrmPrincipal.dskPrincipal.add(iFrmSuporte_VisualizarChamado_Responder);
                iFrmSuporte_VisualizarChamado_Responder.setLocation(
                   dskPrincipal.getWidth()/2 - iFrmSuporte_VisualizarChamado_Responder.getWidth()/2,
                   dskPrincipal.getHeight()/2 - iFrmSuporte_VisualizarChamado_Responder.getHeight()/2);
                iFrmSuporte_VisualizarChamado_Responder.show();
        }
        
        try{
            iFrmSuporte_VisualizarChamado_Responder.setSelected(true);
            iFrmSuporte_VisualizarChamado_Responder.toFront();
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnSuporte_VisualizarChamado_ResponderActionPerformed

    private void btnSuporte_VisualizarChamado_FinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuporte_VisualizarChamado_FinalizarActionPerformed
        
        if(JOptionPane.showConfirmDialog(this, "Finalizar Chamado #"+chamado.getChamadoId()+" ?","ATENÇÃO",JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            chamado.finalizaChamado(chamado);
            JOptionPane.showMessageDialog(this, "Chamado finalizado com sucesso!","SUCESSO",JOptionPane.INFORMATION_MESSAGE);
            dispose();
            IFrmSuporte.carregarTabelaChamados(null, -1);
        }else{
            JOptionPane.showMessageDialog(this, "Finalização de chamado cancelado!","ATENÇÃO",JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btnSuporte_VisualizarChamado_FinalizarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuporte_VisualizarChamado_Finalizar;
    private javax.swing.JButton btnSuporte_VisualizarChamado_Responder;
    private javax.swing.JButton btnSuporte_VisualizarChamado_VisualizarResposta;
    private javax.swing.JFormattedTextField frmtSuporte_VisualizarChamado_DataCriacao;
    private javax.swing.JFormattedTextField frmtSuporte_VisualizarChamado_DataFinalizacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblSuporte_VisualizarChamado_DataFinalizacao;
    private static javax.swing.JTable tblSuporte_VisualizarChamado_Chamado;
    private javax.swing.JTextField txtSuporte_VisualizarChamado_Assunto;
    private javax.swing.JTextField txtSuporte_VisualizarChamado_Responsavel;
    private javax.swing.JTextField txtSuporte_VisualizarChamado_Situacao;
    private javax.swing.JTextField txtSuporte_VisualizarChamado_Solicitante;
    // End of variables declaration//GEN-END:variables
}
