/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Chamado;
import controller.Resposta;

/**
 *
 * @author Urbanski
 */
public class IFrmSuporte_VisualizarChamado_Responder extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrmSuporte_VisualizarChamado_Responder
     */
    private Chamado chamado = new Chamado();
    private Resposta resposta = new Resposta();
    
    public IFrmSuporte_VisualizarChamado_Responder(int chamadoId) {
        initComponents();
        chamado = chamado.retornaChamado(chamadoId);
        populaCampos();
    }

    public void populaCampos(){
        txtSuporte_VisualizarChamado_Responder_Protocolo.setText("#"+chamado.getChamadoId());
        txtSuporte_VisualizarChamado_Responder_Assunto.setText(chamado.getAssunto());
    }
    
    public void responderChamado(){
        resposta.setChamado(chamado);
        resposta.setResposta(txtSuporte_VisualizarChamado_Responder_Resposta.getText());
        resposta.cadastraResposta(resposta);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSuporte_VisualizarChamado_Responder_Protocolo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtSuporte_VisualizarChamado_Responder_Assunto = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSuporte_VisualizarChamado_Responder_Resposta = new javax.swing.JTextArea();
        btnSuporte_VisualizarChamado_Responder_Responder = new javax.swing.JButton();

        setClosable(true);
        setTitle("Responder Chamado");
        setToolTipText("");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Resposta"));

        jLabel1.setText("Protocolo");

        txtSuporte_VisualizarChamado_Responder_Protocolo.setEditable(false);

        jLabel2.setText("Assunto");

        txtSuporte_VisualizarChamado_Responder_Assunto.setEditable(false);

        jLabel3.setText("Resposta");

        txtSuporte_VisualizarChamado_Responder_Resposta.setColumns(20);
        txtSuporte_VisualizarChamado_Responder_Resposta.setRows(5);
        jScrollPane1.setViewportView(txtSuporte_VisualizarChamado_Responder_Resposta);

        btnSuporte_VisualizarChamado_Responder_Responder.setText("Responder");
        btnSuporte_VisualizarChamado_Responder_Responder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuporte_VisualizarChamado_Responder_ResponderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSuporte_VisualizarChamado_Responder_Protocolo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtSuporte_VisualizarChamado_Responder_Assunto, javax.swing.GroupLayout.PREFERRED_SIZE, 351, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuporte_VisualizarChamado_Responder_Responder))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSuporte_VisualizarChamado_Responder_Protocolo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSuporte_VisualizarChamado_Responder_Assunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSuporte_VisualizarChamado_Responder_Responder, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuporte_VisualizarChamado_Responder_ResponderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuporte_VisualizarChamado_Responder_ResponderActionPerformed
        responderChamado();
        IFrmSuporte_VisualizarChamado.popularTabelaChamado();
        dispose();
    }//GEN-LAST:event_btnSuporte_VisualizarChamado_Responder_ResponderActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuporte_VisualizarChamado_Responder_Responder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtSuporte_VisualizarChamado_Responder_Assunto;
    private javax.swing.JTextField txtSuporte_VisualizarChamado_Responder_Protocolo;
    private javax.swing.JTextArea txtSuporte_VisualizarChamado_Responder_Resposta;
    // End of variables declaration//GEN-END:variables
}
