/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Acesso;
import controller.Endereco;
import controller.Pessoa;
import controller.Usuario;
import controller.Caixa;
import controller.Chamado;
import java.text.SimpleDateFormat;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Urbanski
 */
public class IFrmPainel extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrmPainel
     */
    /*
        Objetoss instanciados
    */
    private Pessoa pessoa = null;
    private Endereco endereco = null;
    private static Usuario usuario = new Usuario();
    private Chamado chamado = new Chamado();
    private Acesso ultAcesso = null;
    private Caixa ultCaixa = null;
    private Usuario usuarioPainel = new Usuario();
    
    /*
        Outras instanciações
    */
    private static Iterator i = null;
    private static DefaultTableModel dtmUsuario = null;
    
    /*
        Formatação de datas
    */
    private static SimpleDateFormat formatoData = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
    private SimpleDateFormat dataExibicao = new SimpleDateFormat("ddMMYYYY HHmmss");
    
    /*
        Metodos da classe
    */
    public static void popularTabelaUsuario(String pesquisa, int filtro){
        dtmUsuario = (DefaultTableModel)tblPainel_Usuariol_Usuario.getModel();
        dtmUsuario.setNumRows(0);
        
        if(filtro < 0){
            i = usuario.retornaUsuario();

            while(i.hasNext()){
                usuario = (Usuario)i.next();
                dtmUsuario.addRow(usuario.getUsuario());
            }
        }else{
            i = usuario.retornaUsuario(pesquisa, filtro);

            while(i.hasNext()){
                usuario = (Usuario)i.next();
                dtmUsuario.addRow(usuario.getUsuario());
            }
        }
    }
    
    public void popularCamposPerfil(){
        this.usuarioPainel = FrmPrincipal.usuario;
        txtPainel_Perfil_Nome.setText(FrmPrincipal.usuario.getPessoa().getNome());
        txtPainel_Perfil_Email.setText(FrmPrincipal.usuario.getPessoa().getEmail());
        txtPainel_Perfil_NivelAcesso.setText(FrmPrincipal.usuario.getNivelacesso().getNivel().toString());
        txtPainel_Perfil_TelFixo.setText(FrmPrincipal.usuario.getPessoa().getTelFixo());
        txtPainel_Perfil_TelCel.setText(FrmPrincipal.usuario.getPessoa().getTelCel());
        frmtPainel_Perfil_Cpf.setText(FrmPrincipal.usuario.getCpf());
        frmtPainel_Perfil_DNasc.setText(formatoData.format(FrmPrincipal.usuario.getDataNasc()));
        frmtPainel_Perfil_RG.setText(FrmPrincipal.usuario.getRg());
        txtPainel_Perfil_qtdChamados.setText(String.valueOf(chamado.totalChamado(FrmPrincipal.usuario)));
        if(FrmPrincipal.caixa != null){
            frmtPainel_Perfil_CaixaAberto.setText(dataExibicao.format(FrmPrincipal.caixa.getDataInicio()));
            txtPainel_Perfil_ValorInicial.setText(String.valueOf("R$"+IFrmFinanceiro.saldoInicial));
        
        }
        if(ultAcesso != null){
            frmtPainel_Perfil_UltimoAcesso.setText(dataExibicao.format(this.ultAcesso.getDataInicio()));
            frmtPainel_Perfil_FimUltimoAcesso.setText(dataExibicao.format(this.ultAcesso.getDataFim()));
        }else{
            frmtPainel_Perfil_FimUltimoAcesso.setText("");
            frmtPainel_Perfil_UltimoAcesso.setText("");
        }
    }
    
    public static void atualizaTabelaUsuario(){
        if(txtPainel_Usuario_Pesquisa.getText().equals("")){
            popularTabelaUsuario(null, -1);
        }else{
            popularTabelaUsuario(txtPainel_Usuario_Pesquisa.getText(), cmbPainel_Usuario_Filtro.getSelectedIndex());
        }
    }
    
    public IFrmPainel(Usuario usuario, Acesso acesso) {
        ultAcesso = new Acesso().retornaUltimoAcesso(acesso.getAcessoId()-1);
        ultCaixa  = new Caixa().retornaUltimoCaixa();
        initComponents();
        if(FrmPrincipal.usuario.getNivelacesso().getNivel() == 1){
            GuiaPainel_Usuario.remove(1);
        }else{
            atualizaTabelaUsuario();
        }
        
        popularCamposPerfil();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GuiaPainel_Usuario = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPainel_Perfil_Nome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtPainel_Perfil_Email = new javax.swing.JTextField();
        txtPainel_Perfil_TelFixo = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtPainel_Perfil_TelCel = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        frmtPainel_Perfil_DNasc = new javax.swing.JFormattedTextField();
        frmtPainel_Perfil_RG = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        frmtPainel_Perfil_Cpf = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        frmtPainel_Perfil_UltimoAcesso = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        frmtPainel_Perfil_FimUltimoAcesso = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        frmtPainel_Perfil_CaixaAberto = new javax.swing.JFormattedTextField();
        txtPainel_Perfil_NivelAcesso = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtPainel_Perfil_ValorInicial = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtPainel_Perfil_qtdChamados = new javax.swing.JTextField();
        btnPainel_AlterarSenha = new javax.swing.JButton();
        pnlPainel_Usuario = new javax.swing.JPanel();
        txtPainel_Usuario_Pesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPainel_Usuariol_Usuario = new javax.swing.JTable();
        btnPainel_Usuario_NovoColaborador = new javax.swing.JButton();
        cmbPainel_Usuario_Filtro = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        btnPainel_Usuario_ExcluirColaborador = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();

        setClosable(true);
        setMaximizable(true);
        setTitle("Painel");

        jLabel1.setText("Nome");

        txtPainel_Perfil_Nome.setEditable(false);

        jLabel2.setText("Email");

        txtPainel_Perfil_Email.setEditable(false);

        txtPainel_Perfil_TelFixo.setEditable(false);
        try {
            txtPainel_Perfil_TelFixo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel4.setText("Tel. Fixo");

        jLabel5.setText("Tel. Celular");

        txtPainel_Perfil_TelCel.setEditable(false);
        try {
            txtPainel_Perfil_TelCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel3.setText("Data de nascimento");

        frmtPainel_Perfil_DNasc.setEditable(false);
        try {
            frmtPainel_Perfil_DNasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        frmtPainel_Perfil_RG.setEditable(false);
        try {
            frmtPainel_Perfil_RG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel6.setText("RG");

        frmtPainel_Perfil_Cpf.setEditable(false);
        try {
            frmtPainel_Perfil_Cpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel7.setText("CPF");

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Acessos"));

        jLabel8.setText("Inicio Ult. Acesso");

        frmtPainel_Perfil_UltimoAcesso.setEditable(false);
        try {
            frmtPainel_Perfil_UltimoAcesso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/#### ##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel9.setText("Fim Ult. Acesso");

        frmtPainel_Perfil_FimUltimoAcesso.setEditable(false);
        try {
            frmtPainel_Perfil_FimUltimoAcesso.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/#### ##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel10.setText("Caixa Aberto");

        frmtPainel_Perfil_CaixaAberto.setEditable(false);
        try {
            frmtPainel_Perfil_CaixaAberto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/#### ##:##:##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        txtPainel_Perfil_NivelAcesso.setEditable(false);

        jLabel12.setText("Nivel de acesso");

        jLabel13.setText("Valor inicial");

        txtPainel_Perfil_ValorInicial.setEditable(false);

        jLabel14.setText("Qtd. Chamados atendidos");

        txtPainel_Perfil_qtdChamados.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel10))
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(frmtPainel_Perfil_UltimoAcesso, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(frmtPainel_Perfil_CaixaAberto))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel13))
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(frmtPainel_Perfil_FimUltimoAcesso)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(15, 15, 15)
                        .addComponent(txtPainel_Perfil_NivelAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txtPainel_Perfil_ValorInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel14)
                        .addGap(15, 15, 15)
                        .addComponent(txtPainel_Perfil_qtdChamados, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel12)
                        .addComponent(txtPainel_Perfil_NivelAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(frmtPainel_Perfil_UltimoAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(frmtPainel_Perfil_FimUltimoAcesso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(txtPainel_Perfil_qtdChamados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(txtPainel_Perfil_ValorInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(frmtPainel_Perfil_CaixaAberto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnPainel_AlterarSenha.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/png/008-login-2.png"))); // NOI18N
        btnPainel_AlterarSenha.setText("Alterar Senha");
        btnPainel_AlterarSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPainel_AlterarSenhaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnPainel_AlterarSenha)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(15, 15, 15)
                                .addComponent(frmtPainel_Perfil_DNasc, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(15, 15, 15)
                                .addComponent(txtPainel_Perfil_TelFixo, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabel6)
                                .addGap(15, 15, 15)
                                .addComponent(frmtPainel_Perfil_RG, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(65, 65, 65)
                                .addComponent(jLabel7)
                                .addGap(15, 15, 15)
                                .addComponent(frmtPainel_Perfil_Cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(jLabel5)
                                .addGap(15, 15, 15)
                                .addComponent(txtPainel_Perfil_TelCel, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(15, 15, 15)
                        .addComponent(txtPainel_Perfil_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(15, 15, 15)
                        .addComponent(txtPainel_Perfil_Email, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addGap(15, 15, 15))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPainel_Perfil_Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(txtPainel_Perfil_Email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(frmtPainel_Perfil_Cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(frmtPainel_Perfil_RG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(frmtPainel_Perfil_DNasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtPainel_Perfil_TelCel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(txtPainel_Perfil_TelFixo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPainel_AlterarSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        GuiaPainel_Usuario.addTab("Perfil", jPanel1);

        pnlPainel_Usuario.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                pnlPainel_UsuarioComponentShown(evt);
            }
        });

        txtPainel_Usuario_Pesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPainel_Usuario_PesquisaKeyReleased(evt);
            }
        });

        tblPainel_Usuariol_Usuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOME", "CPF", "LOGIN", "DATA CADASTRO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblPainel_Usuariol_Usuario);

        btnPainel_Usuario_NovoColaborador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/png/003-social-1.png"))); // NOI18N
        btnPainel_Usuario_NovoColaborador.setText("Novo Colaborador");
        btnPainel_Usuario_NovoColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPainel_Usuario_NovoColaboradorActionPerformed(evt);
            }
        });

        cmbPainel_Usuario_Filtro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "NOME", "CPF", "LOGIN" }));

        jLabel11.setText("Pesquisar por");

        btnPainel_Usuario_ExcluirColaborador.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/010-remove-user.png"))); // NOI18N
        btnPainel_Usuario_ExcluirColaborador.setText("Excluir Colaborador");
        btnPainel_Usuario_ExcluirColaborador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPainel_Usuario_ExcluirColaboradorActionPerformed(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/025-magnifier.png"))); // NOI18N

        javax.swing.GroupLayout pnlPainel_UsuarioLayout = new javax.swing.GroupLayout(pnlPainel_Usuario);
        pnlPainel_Usuario.setLayout(pnlPainel_UsuarioLayout);
        pnlPainel_UsuarioLayout.setHorizontalGroup(
            pnlPainel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPainel_UsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlPainel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlPainel_UsuarioLayout.createSequentialGroup()
                        .addComponent(btnPainel_Usuario_NovoColaborador)
                        .addGap(86, 86, 86)
                        .addComponent(btnPainel_Usuario_ExcluirColaborador)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlPainel_UsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPainel_Usuario_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(jLabel11)
                        .addGap(18, 18, 18)
                        .addComponent(cmbPainel_Usuario_Filtro, 0, 143, Short.MAX_VALUE)))
                .addGap(15, 15, 15))
        );
        pnlPainel_UsuarioLayout.setVerticalGroup(
            pnlPainel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlPainel_UsuarioLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlPainel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 26, Short.MAX_VALUE)
                    .addComponent(txtPainel_Usuario_Pesquisa, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cmbPainel_Usuario_Filtro, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlPainel_UsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPainel_Usuario_NovoColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPainel_Usuario_ExcluirColaborador, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        GuiaPainel_Usuario.addTab("Usuários", pnlPainel_Usuario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(GuiaPainel_Usuario)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(GuiaPainel_Usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPainel_Usuario_NovoColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPainel_Usuario_NovoColaboradorActionPerformed
        IFrmPainel_Cadastro iFrmPainel_Cadastro = null;
        
        if(iFrmPainel_Cadastro == null){
            iFrmPainel_Cadastro = new IFrmPainel_Cadastro(null);
        }
        if(!iFrmPainel_Cadastro.isVisible()){
            FrmPrincipal.dskPrincipal.add(iFrmPainel_Cadastro);
            iFrmPainel_Cadastro.setLocation(
                   FrmPrincipal.dskPrincipal.getWidth()/2 - iFrmPainel_Cadastro.getWidth()/2,
                   FrmPrincipal.dskPrincipal.getHeight()/2 - iFrmPainel_Cadastro.getHeight()/2);
            iFrmPainel_Cadastro.show();
        }
        
        try{
            iFrmPainel_Cadastro.setSelected(true);
            iFrmPainel_Cadastro.toFront();
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnPainel_Usuario_NovoColaboradorActionPerformed

    private void btnPainel_Usuario_ExcluirColaboradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPainel_Usuario_ExcluirColaboradorActionPerformed
        if(JOptionPane.showConfirmDialog(null, "Deseja realmente excluir esse colaborador\n"+usuario.getPessoa().getNome()+" ?") == JOptionPane.YES_OPTION){
            int linha = tblPainel_Usuariol_Usuario.getSelectedRow();
            if(linha >=0){
                Usuario usuario = new Usuario().retornaUsuario(Integer.valueOf(dtmUsuario.getValueAt(linha, 0).toString()));
                if(usuario.getUsuarioId() != FrmPrincipal.usuario.getUsuarioId()){
                 
                    if(usuario.verificaIntegridade(usuario)){
                        Endereco endereco = new Endereco().retornaEndereco(usuario.getPessoa().getPessoaId());
                        Pessoa pessoa = new Pessoa();
                        pessoa = usuario.getPessoa();
                        if(usuario.excluirUsuario(usuario)){
                            endereco.excluirEndereco(endereco);
                            pessoa.excluirPessoa(pessoa);
                            JOptionPane.showMessageDialog(this, "Usuário "+usuario.getLogin()+" excluido");
                        }else{
                            JOptionPane.showMessageDialog(this, "Não foi possivel excluir o usuario");
                        }
                    }else{
                        JOptionPane.showMessageDialog(this, "Não é possivel excluir esse colaborador pois existe Acessos, Chamados ou Caixas vinculados a ele.","ATENÇÃO",JOptionPane.ERROR_MESSAGE);
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Usuário não pode ser excluido, pois ele encontra-se logado.","ATENÇÃO",JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Selecione um usuário para ser excluido.","ATENÇÃO",JOptionPane.ERROR_MESSAGE);
            }
                
        }else{
            
        }
    
    }//GEN-LAST:event_btnPainel_Usuario_ExcluirColaboradorActionPerformed

    private void txtPainel_Usuario_PesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPainel_Usuario_PesquisaKeyReleased
        atualizaTabelaUsuario();
    }//GEN-LAST:event_txtPainel_Usuario_PesquisaKeyReleased

    private void pnlPainel_UsuarioComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_pnlPainel_UsuarioComponentShown
        atualizaTabelaUsuario();
    }//GEN-LAST:event_pnlPainel_UsuarioComponentShown

    private void btnPainel_AlterarSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPainel_AlterarSenhaActionPerformed
        IFrmPainel_TrocarSenha iFrmPainel_TrocaSenha = null;
        
        if(iFrmPainel_TrocaSenha == null){
            iFrmPainel_TrocaSenha = new IFrmPainel_TrocarSenha(FrmPrincipal.usuario);
        }
        if(!iFrmPainel_TrocaSenha.isVisible()){
            FrmPrincipal.dskPrincipal.add(iFrmPainel_TrocaSenha);
            iFrmPainel_TrocaSenha.setLocation(
                   FrmPrincipal.dskPrincipal.getWidth()/2 - iFrmPainel_TrocaSenha.getWidth()/2,
                   FrmPrincipal.dskPrincipal.getHeight()/2 - iFrmPainel_TrocaSenha.getHeight()/2);
            iFrmPainel_TrocaSenha.show();
        }
        
        try{
            iFrmPainel_TrocaSenha.setSelected(true);
            iFrmPainel_TrocaSenha.toFront();
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnPainel_AlterarSenhaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane GuiaPainel_Usuario;
    private javax.swing.JButton btnPainel_AlterarSenha;
    private javax.swing.JButton btnPainel_Usuario_ExcluirColaborador;
    private javax.swing.JButton btnPainel_Usuario_NovoColaborador;
    private static javax.swing.JComboBox<String> cmbPainel_Usuario_Filtro;
    public static javax.swing.JFormattedTextField frmtPainel_Perfil_CaixaAberto;
    private javax.swing.JFormattedTextField frmtPainel_Perfil_Cpf;
    private javax.swing.JFormattedTextField frmtPainel_Perfil_DNasc;
    private javax.swing.JFormattedTextField frmtPainel_Perfil_FimUltimoAcesso;
    private javax.swing.JFormattedTextField frmtPainel_Perfil_RG;
    private javax.swing.JFormattedTextField frmtPainel_Perfil_UltimoAcesso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlPainel_Usuario;
    public static javax.swing.JTable tblPainel_Usuariol_Usuario;
    private javax.swing.JTextField txtPainel_Perfil_Email;
    private javax.swing.JTextField txtPainel_Perfil_NivelAcesso;
    private javax.swing.JTextField txtPainel_Perfil_Nome;
    private javax.swing.JFormattedTextField txtPainel_Perfil_TelCel;
    private javax.swing.JFormattedTextField txtPainel_Perfil_TelFixo;
    public static javax.swing.JTextField txtPainel_Perfil_ValorInicial;
    private javax.swing.JTextField txtPainel_Perfil_qtdChamados;
    private static javax.swing.JTextField txtPainel_Usuario_Pesquisa;
    // End of variables declaration//GEN-END:variables
}
