/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Chamado;
import controller.Resposta;
import controller.Situacao;
import controller.Usuario;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Urbanski
 */
public class IFrmSuporte extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrmSuporte
     */
    private int chamadoId;
    private Chamado chamado = null;
    private Resposta resposta = null;
    private Situacao situacao = new Situacao();
    static Usuario usuario = null;
    private static Iterator i = null;
    private static DefaultTableModel dtmChamado = null;
    
    public void cadastraChamado(){
        
        chamado = new Chamado(situacao.retornaSituacao(7), txtSuporte_NovoChamado_Assunto.getText() , usuario);
        resposta = new Resposta(chamado, txtSuporte_NovoChamado_Descricao.getText(), 0);
        
        if(chamado.cadastraChamado(chamado) && resposta.cadastraResposta(resposta)){
            JOptionPane.showMessageDialog(this, "Chamado #"+chamado.getChamadoId()+" criado com sucesso!","SUCESSO",JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "Chamado não foi aberto, favor verificar os campos!","ATENÇÃO",JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public static void carregarTabelaChamados(String pesquisa, int filtro){
        dtmChamado = null;
        Chamado c = new Chamado();
        dtmChamado = (DefaultTableModel)tblSuporte_VisualizarChamado_Chamado.getModel();
        dtmChamado.setNumRows(0);
        

        i = c.retornaChamado(pesquisa, filtro);
        
        
        while(i.hasNext()){
            c = (Chamado)i.next();
            dtmChamado.addRow(c.getChamado());
        }
        
    }
    
    public void visualizarChamado(){
        int linha = tblSuporte_VisualizarChamado_Chamado.getSelectedRow();
        
        if(linha >= 0){
            chamadoId = Integer.valueOf(dtmChamado.getValueAt(linha, 0).toString().replace("#", ""));
            
            IFrmSuporte_VisualizarChamado iFrmSuporte_Visualizar = new IFrmSuporte_VisualizarChamado(chamadoId);
        
            if(!iFrmSuporte_Visualizar.isVisible()){
                FrmPrincipal.dskPrincipal.add(iFrmSuporte_Visualizar);
                iFrmSuporte_Visualizar.setLocation(
                    FrmPrincipal.dskPrincipal.getWidth()/2 - iFrmSuporte_Visualizar.getWidth()/2,
                    FrmPrincipal.dskPrincipal.getHeight()/2 - iFrmSuporte_Visualizar.getHeight()/2);
                iFrmSuporte_Visualizar.show();
            }

            try{
                iFrmSuporte_Visualizar.setSelected(true);
                iFrmSuporte_Visualizar.toFront();
            }catch(Exception ex){
                ex.printStackTrace();
            }
            }else{
                JOptionPane.showMessageDialog(this, "Deve ser selecionado um chamado para visualização!","ATENÇÃO",JOptionPane.ERROR_MESSAGE);
            }
        
    }
    
    public void limpaCampos(){
        txtSuporte_NovoChamado_Assunto.setText("");
        txtSuporte_NovoChamado_Atendente.setText("");
        txtSuporte_NovoChamado_Descricao.setText("");
        txtSuporte_NovoChamado_Solicitante.setText("");
        txtSuporte_VisualizarChamado_Pesquisa.setText("");
    }
    
    public IFrmSuporte() {
        initComponents();
        carregarTabelaChamados(null, -1);
        lblQuantidadeChamados.setText("Total de chamados: "+String.valueOf(dtmChamado.getRowCount()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSuporte_NovoChamado_Solicitante = new javax.swing.JTextField();
        btnSuporte_NovoChamado_AdicionarSolicitante = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtSuporte_NovoChamado_Atendente = new javax.swing.JTextField();
        btnSuporte_NovoChamado_AdicionarAtendente = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtSuporte_NovoChamado_Assunto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtSuporte_NovoChamado_Descricao = new javax.swing.JTextArea();
        btnSuporte_NovoChamado_CriarChamado = new javax.swing.JButton();
        btnSuporte_NovoChamado_Limpar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSuporte_VisualizarChamado_Chamado = new javax.swing.JTable();
        btnSuporte_VisualizarChamado_VisualizarChamado = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtSuporte_VisualizarChamado_Pesquisa = new javax.swing.JTextField();
        cmbSuporte_VisualizarChamado_Filtro = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        lblQuantidadeChamados = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Suporte");
        setPreferredSize(new java.awt.Dimension(823, 436));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Abrir Chamado"));

        jLabel1.setText("Solicitante");

        btnSuporte_NovoChamado_AdicionarSolicitante.setText("+");

        jLabel2.setText("Vincular Atendente");

        btnSuporte_NovoChamado_AdicionarAtendente.setText("+");
        btnSuporte_NovoChamado_AdicionarAtendente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuporte_NovoChamado_AdicionarAtendenteActionPerformed(evt);
            }
        });

        jLabel3.setText("Assunto");

        jLabel4.setText("Descrição");

        txtSuporte_NovoChamado_Descricao.setColumns(20);
        txtSuporte_NovoChamado_Descricao.setRows(5);
        jScrollPane1.setViewportView(txtSuporte_NovoChamado_Descricao);

        btnSuporte_NovoChamado_CriarChamado.setText("Criar Chamado");
        btnSuporte_NovoChamado_CriarChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuporte_NovoChamado_CriarChamadoActionPerformed(evt);
            }
        });

        btnSuporte_NovoChamado_Limpar.setText("Limpar");
        btnSuporte_NovoChamado_Limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuporte_NovoChamado_LimparActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSuporte_NovoChamado_Solicitante, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnSuporte_NovoChamado_AdicionarSolicitante))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(18, 18, 18)
                            .addComponent(txtSuporte_NovoChamado_Atendente, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnSuporte_NovoChamado_AdicionarAtendente))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSuporte_NovoChamado_Assunto, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel4)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(btnSuporte_NovoChamado_CriarChamado)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSuporte_NovoChamado_Limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(67, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSuporte_NovoChamado_Solicitante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuporte_NovoChamado_AdicionarSolicitante, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtSuporte_NovoChamado_Atendente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuporte_NovoChamado_AdicionarAtendente, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSuporte_NovoChamado_Assunto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSuporte_NovoChamado_Limpar, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(btnSuporte_NovoChamado_CriarChamado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Novo Chamado", jPanel1);

        jPanel2.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel2ComponentShown(evt);
            }
        });

        tblSuporte_VisualizarChamado_Chamado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PROTOCOLO", "ASSUNTO", "SOLICITANTE", "DATA", "SITUAÇÃO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblSuporte_VisualizarChamado_Chamado);
        if (tblSuporte_VisualizarChamado_Chamado.getColumnModel().getColumnCount() > 0) {
            tblSuporte_VisualizarChamado_Chamado.getColumnModel().getColumn(0).setResizable(false);
            tblSuporte_VisualizarChamado_Chamado.getColumnModel().getColumn(0).setPreferredWidth(15);
            tblSuporte_VisualizarChamado_Chamado.getColumnModel().getColumn(1).setResizable(false);
            tblSuporte_VisualizarChamado_Chamado.getColumnModel().getColumn(1).setPreferredWidth(100);
            tblSuporte_VisualizarChamado_Chamado.getColumnModel().getColumn(2).setResizable(false);
            tblSuporte_VisualizarChamado_Chamado.getColumnModel().getColumn(3).setResizable(false);
            tblSuporte_VisualizarChamado_Chamado.getColumnModel().getColumn(3).setPreferredWidth(20);
            tblSuporte_VisualizarChamado_Chamado.getColumnModel().getColumn(4).setResizable(false);
            tblSuporte_VisualizarChamado_Chamado.getColumnModel().getColumn(4).setPreferredWidth(20);
        }

        btnSuporte_VisualizarChamado_VisualizarChamado.setText("Visualizar Chamado");
        btnSuporte_VisualizarChamado_VisualizarChamado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuporte_VisualizarChamado_VisualizarChamadoActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/025-magnifier.png"))); // NOI18N

        txtSuporte_VisualizarChamado_Pesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSuporte_VisualizarChamado_PesquisaKeyReleased(evt);
            }
        });

        cmbSuporte_VisualizarChamado_Filtro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Protocolo", "Assunto", "Solicitante", "Situação" }));

        jLabel6.setText("Pesquisa por");

        lblQuantidadeChamados.setText("Chamados");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtSuporte_VisualizarChamado_Pesquisa)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbSuporte_VisualizarChamado_Filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnSuporte_VisualizarChamado_VisualizarChamado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblQuantidadeChamados, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtSuporte_VisualizarChamado_Pesquisa)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbSuporte_VisualizarChamado_Filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSuporte_VisualizarChamado_VisualizarChamado, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                    .addComponent(lblQuantidadeChamados))
                .addGap(10, 10, 10))
        );

        jTabbedPane1.addTab("Visualizar Chamados", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jTabbedPane1)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSuporte_NovoChamado_AdicionarAtendenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuporte_NovoChamado_AdicionarAtendenteActionPerformed
        IFrmSuporte_SelecionaUsuario iFrmSuporte_SelecionarUsuario = null;
        
        iFrmSuporte_SelecionarUsuario = new IFrmSuporte_SelecionaUsuario();
        
        if(!iFrmSuporte_SelecionarUsuario.isVisible()){
            FrmPrincipal.dskPrincipal.add(iFrmSuporte_SelecionarUsuario);
            iFrmSuporte_SelecionarUsuario.setLocation(
                FrmPrincipal.dskPrincipal.getWidth()/2 - iFrmSuporte_SelecionarUsuario.getWidth()/2,
                FrmPrincipal.dskPrincipal.getHeight()/2 - iFrmSuporte_SelecionarUsuario.getHeight()/2);
            iFrmSuporte_SelecionarUsuario.show();
        }
        
        try{
            iFrmSuporte_SelecionarUsuario.setSelected(true);
            iFrmSuporte_SelecionarUsuario.toFront();
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }//GEN-LAST:event_btnSuporte_NovoChamado_AdicionarAtendenteActionPerformed

    private void btnSuporte_NovoChamado_CriarChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuporte_NovoChamado_CriarChamadoActionPerformed
        cadastraChamado();
    }//GEN-LAST:event_btnSuporte_NovoChamado_CriarChamadoActionPerformed

    private void jPanel2ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel2ComponentShown
        carregarTabelaChamados(null, -1);
    }//GEN-LAST:event_jPanel2ComponentShown

    private void txtSuporte_VisualizarChamado_PesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSuporte_VisualizarChamado_PesquisaKeyReleased
        if(txtSuporte_VisualizarChamado_Pesquisa.equals("")){
            carregarTabelaChamados(null, -1);
        }else{
            carregarTabelaChamados(txtSuporte_VisualizarChamado_Pesquisa.getText(), cmbSuporte_VisualizarChamado_Filtro.getSelectedIndex());
        }
    }//GEN-LAST:event_txtSuporte_VisualizarChamado_PesquisaKeyReleased

    private void btnSuporte_VisualizarChamado_VisualizarChamadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuporte_VisualizarChamado_VisualizarChamadoActionPerformed
        visualizarChamado();
    }//GEN-LAST:event_btnSuporte_VisualizarChamado_VisualizarChamadoActionPerformed

    private void btnSuporte_NovoChamado_LimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuporte_NovoChamado_LimparActionPerformed
        limpaCampos();
    }//GEN-LAST:event_btnSuporte_NovoChamado_LimparActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuporte_NovoChamado_AdicionarAtendente;
    private javax.swing.JButton btnSuporte_NovoChamado_AdicionarSolicitante;
    private javax.swing.JButton btnSuporte_NovoChamado_CriarChamado;
    private javax.swing.JButton btnSuporte_NovoChamado_Limpar;
    private javax.swing.JButton btnSuporte_VisualizarChamado_VisualizarChamado;
    private javax.swing.JComboBox<String> cmbSuporte_VisualizarChamado_Filtro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblQuantidadeChamados;
    public static javax.swing.JTable tblSuporte_VisualizarChamado_Chamado;
    private javax.swing.JTextField txtSuporte_NovoChamado_Assunto;
    public static javax.swing.JTextField txtSuporte_NovoChamado_Atendente;
    private javax.swing.JTextArea txtSuporte_NovoChamado_Descricao;
    private javax.swing.JTextField txtSuporte_NovoChamado_Solicitante;
    private javax.swing.JTextField txtSuporte_VisualizarChamado_Pesquisa;
    // End of variables declaration//GEN-END:variables
}
