/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Contapagar;
import controller.Fornecedor;
import controller.Movimento;
import controller.Tipomovimento;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Urbanski
 */
public class IFrmContaPagar_VisualizarContaPagar extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFrmContaPagar_VisualizarAVencer
     */
    private SimpleDateFormat dataExibicao = new SimpleDateFormat("ddMMYYYY");
    private int contaPagarId;
    private Contapagar conta = new Contapagar();
    private Movimento movimento = null;
    private Tipomovimento tipoMovimento = null;
    private Fornecedor fornecedor = null;
    
    public IFrmContaPagar_VisualizarContaPagar(int contaPagarId) {
        initComponents();
        this.contaPagarId = contaPagarId;
        carregaConta();
    }
    
    private void carregaConta(){
        
        conta = conta.retornaContaPagar(contaPagarId);
        txtAgendarPagamento_VisualizarConta_NDocumento.setText(String.valueOf(conta.getNumeroDoc()));
        spnAgendarPagamento_VisualizarConta_Valor.setValue(conta.getValor());
        spnAgendarPagamento_VisualizarConta_Multa.setValue(conta.getMulta());
        spnAgendarPagamento_VisualizarConta_Desconto.setValue(conta.getDesconto());
        txtAgendarPagamento_Descricao.setText(conta.getTransacao().getDescricao());
        frmtAgendarPagamento_VisualizarConta_Vencimento.setText(dataExibicao.format(conta.getDataVencimento()));
        frmtAgendarPagamento_VisualizarConta_Emissao.setText(dataExibicao.format(conta.getDataEmissao()));
        txtAgendarPagamento_VisualizarConta_RazaoSocial.setText(conta.getFornecedor().getRazao());
        txtAgendarPagamento_VisualizarConta_Cnpj.setText(conta.getFornecedor().getCnpj());
        txtAgendarPagamento_VisualizarConta_NomeFantasia.setText(conta.getFornecedor().getPessoa().getNome());
        txtAgendarPagamento_VisualizarConta_CodigoFornecedor.setText(String.valueOf(conta.getFornecedor().getFornecedorId()));
        spnAgendarPagamento_VisualizarConta_Total.setValue(conta.getTotal());
        txtAgendarPagamento_VisualizarConta_Situacao.setText(conta.getTransacao().getSituacao().getStatus());
        if(conta.getTransacao().getSituacao().getSituacaoId() == 2){
            btnAgendarPagamento_VisualizarConta_RealizarPagamento.setVisible(false);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgendarPagamento_VisualizarConta_RealizarPagamento = new javax.swing.JButton();
        btnAgendarPagamento_VisualizarConta_Cancelar = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        scrlDescricao = new javax.swing.JScrollPane();
        txtAgendarPagamento_Descricao = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtAgendarPagamento_VisualizarConta_NDocumento = new javax.swing.JTextField();
        frmtAgendarPagamento_VisualizarConta_Vencimento = new javax.swing.JFormattedTextField();
        frmtAgendarPagamento_VisualizarConta_Emissao = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtAgendarPagamento_VisualizarConta_Situacao = new javax.swing.JTextField();
        spnAgendarPagamento_VisualizarConta_Valor = new javax.swing.JFormattedTextField();
        spnAgendarPagamento_VisualizarConta_Desconto = new javax.swing.JFormattedTextField();
        spnAgendarPagamento_VisualizarConta_Multa = new javax.swing.JFormattedTextField();
        spnAgendarPagamento_VisualizarConta_Total = new javax.swing.JFormattedTextField();
        jPanel11 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtAgendarPagamento_VisualizarConta_RazaoSocial = new javax.swing.JTextField();
        txtAgendarPagamento_VisualizarConta_NomeFantasia = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAgendarPagamento_VisualizarConta_CodigoFornecedor = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        lblNomeFantasia = new javax.swing.JLabel();
        txtAgendarPagamento_VisualizarConta_Cnpj = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Visualização Conta a Pagar");

        btnAgendarPagamento_VisualizarConta_RealizarPagamento.setText("Realizar pagamento");
        btnAgendarPagamento_VisualizarConta_RealizarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarPagamento_VisualizarConta_RealizarPagamentoActionPerformed(evt);
            }
        });

        btnAgendarPagamento_VisualizarConta_Cancelar.setText("Fechar");
        btnAgendarPagamento_VisualizarConta_Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarPagamento_VisualizarConta_CancelarActionPerformed(evt);
            }
        });

        jPanel12.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Informações da conta"));

        jLabel5.setText("Valor");

        jLabel6.setText("Desconto");

        jLabel7.setText("Multa");

        txtAgendarPagamento_Descricao.setEditable(false);
        txtAgendarPagamento_Descricao.setColumns(20);
        txtAgendarPagamento_Descricao.setLineWrap(true);
        txtAgendarPagamento_Descricao.setRows(5);
        scrlDescricao.setViewportView(txtAgendarPagamento_Descricao);

        jLabel9.setText("Emissão");

        jLabel10.setText("Vencimento");

        jLabel8.setText("Descrição");

        jLabel22.setText("Nº Documento");

        txtAgendarPagamento_VisualizarConta_NDocumento.setEditable(false);

        frmtAgendarPagamento_VisualizarConta_Vencimento.setEditable(false);
        try {
            frmtAgendarPagamento_VisualizarConta_Vencimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        frmtAgendarPagamento_VisualizarConta_Emissao.setEditable(false);
        try {
            frmtAgendarPagamento_VisualizarConta_Emissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel11.setText("Total");

        jLabel12.setText("Situação");

        txtAgendarPagamento_VisualizarConta_Situacao.setEditable(false);

        spnAgendarPagamento_VisualizarConta_Valor.setEditable(false);
        spnAgendarPagamento_VisualizarConta_Valor.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));

        spnAgendarPagamento_VisualizarConta_Desconto.setEditable(false);
        spnAgendarPagamento_VisualizarConta_Desconto.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));

        spnAgendarPagamento_VisualizarConta_Multa.setEditable(false);
        spnAgendarPagamento_VisualizarConta_Multa.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));

        spnAgendarPagamento_VisualizarConta_Total.setEditable(false);
        spnAgendarPagamento_VisualizarConta_Total.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("¤#,##0.00"))));

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel22)
                        .addGap(18, 18, 18)
                        .addComponent(txtAgendarPagamento_VisualizarConta_NDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnAgendarPagamento_VisualizarConta_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spnAgendarPagamento_VisualizarConta_Desconto, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnAgendarPagamento_VisualizarConta_Multa, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(spnAgendarPagamento_VisualizarConta_Total, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(scrlDescricao)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(frmtAgendarPagamento_VisualizarConta_Vencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel9)
                                .addGap(22, 22, 22)
                                .addComponent(frmtAgendarPagamento_VisualizarConta_Emissao, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtAgendarPagamento_VisualizarConta_Situacao, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(85, 85, 85))))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel5)
                    .addComponent(txtAgendarPagamento_VisualizarConta_NDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22)
                    .addComponent(jLabel11)
                    .addComponent(spnAgendarPagamento_VisualizarConta_Valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnAgendarPagamento_VisualizarConta_Desconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnAgendarPagamento_VisualizarConta_Multa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(spnAgendarPagamento_VisualizarConta_Total, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addComponent(jLabel8)
                .addGap(14, 14, 14)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(frmtAgendarPagamento_VisualizarConta_Vencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(frmtAgendarPagamento_VisualizarConta_Emissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(txtAgendarPagamento_VisualizarConta_Situacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(scrlDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Fornecedor"));

        jLabel4.setText("Razão Social");

        txtAgendarPagamento_VisualizarConta_RazaoSocial.setEditable(false);

        txtAgendarPagamento_VisualizarConta_NomeFantasia.setEditable(false);

        jLabel3.setText("Código");

        txtAgendarPagamento_VisualizarConta_CodigoFornecedor.setEditable(false);

        jLabel2.setText("CNPJ");

        lblNomeFantasia.setText("Nome Fantasia ");

        txtAgendarPagamento_VisualizarConta_Cnpj.setEditable(false);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel4))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNomeFantasia)))
                .addGap(10, 10, 10)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(txtAgendarPagamento_VisualizarConta_NomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(txtAgendarPagamento_VisualizarConta_Cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addComponent(txtAgendarPagamento_VisualizarConta_RazaoSocial)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(txtAgendarPagamento_VisualizarConta_CodigoFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtAgendarPagamento_VisualizarConta_RazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4))
                    .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtAgendarPagamento_VisualizarConta_CodigoFornecedor)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(19, 19, 19)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtAgendarPagamento_VisualizarConta_NomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNomeFantasia)
                    .addComponent(txtAgendarPagamento_VisualizarConta_Cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(btnAgendarPagamento_VisualizarConta_RealizarPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAgendarPagamento_VisualizarConta_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAgendarPagamento_VisualizarConta_RealizarPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgendarPagamento_VisualizarConta_Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgendarPagamento_VisualizarConta_RealizarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarPagamento_VisualizarConta_RealizarPagamentoActionPerformed
        float saldoAtual = Float.valueOf(IFrmFinanceiro.spnCaixa_SaldoAtual.getValue().toString());
        float totalPagar = Float.valueOf(spnAgendarPagamento_VisualizarConta_Total.getValue().toString());

        if(totalPagar >  saldoAtual) {
            JOptionPane.showMessageDialog(this, "Saldo em caixa insulficiente para realizar pagamento.","ATENÇÃO",JOptionPane.INFORMATION_MESSAGE);
        }else{
            if(JOptionPane.showConfirmDialog(this, "Deseja confirmar o pagamento da conta "+conta.getFornecedor().getPessoa().getNome()+" ?","ATENÇÃO",JOptionPane.OK_CANCEL_OPTION) == JOptionPane.YES_OPTION){
              
                if(conta.atualizarSituacaoContaPagar(conta,2)){
                    conta.atualizaCaixa(conta.getContaPagarId(), FrmPrincipal.caixa.getCaixaId());
                    movimento = new Movimento(FrmPrincipal.caixa, tipoMovimento = new Tipomovimento().retornaTipoMovimento(1), null, conta.getTotal());
                    movimento.cadastraMovimento(movimento);
                    JOptionPane.showMessageDialog(this, "Pagamento realizado!","SUCESSO",JOptionPane.INFORMATION_MESSAGE);
                    dispose();
                }else{
                    JOptionPane.showMessageDialog(this, "Não foi possivel realizar o pagamento!!","ATENÇÃO",JOptionPane.ERROR_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(this, "Pagamento cancelado!!!");
            }
        }
        IFrmFinanceiro.atualizaAllTbl();
    }//GEN-LAST:event_btnAgendarPagamento_VisualizarConta_RealizarPagamentoActionPerformed

    private void btnAgendarPagamento_VisualizarConta_CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarPagamento_VisualizarConta_CancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnAgendarPagamento_VisualizarConta_CancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendarPagamento_VisualizarConta_Cancelar;
    private javax.swing.JButton btnAgendarPagamento_VisualizarConta_RealizarPagamento;
    private javax.swing.JFormattedTextField frmtAgendarPagamento_VisualizarConta_Emissao;
    private javax.swing.JFormattedTextField frmtAgendarPagamento_VisualizarConta_Vencimento;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JLabel lblNomeFantasia;
    private javax.swing.JScrollPane scrlDescricao;
    private javax.swing.JFormattedTextField spnAgendarPagamento_VisualizarConta_Desconto;
    private javax.swing.JFormattedTextField spnAgendarPagamento_VisualizarConta_Multa;
    private javax.swing.JFormattedTextField spnAgendarPagamento_VisualizarConta_Total;
    private javax.swing.JFormattedTextField spnAgendarPagamento_VisualizarConta_Valor;
    private javax.swing.JTextArea txtAgendarPagamento_Descricao;
    private javax.swing.JTextField txtAgendarPagamento_VisualizarConta_Cnpj;
    private javax.swing.JTextField txtAgendarPagamento_VisualizarConta_CodigoFornecedor;
    private javax.swing.JTextField txtAgendarPagamento_VisualizarConta_NDocumento;
    private javax.swing.JTextField txtAgendarPagamento_VisualizarConta_NomeFantasia;
    private javax.swing.JTextField txtAgendarPagamento_VisualizarConta_RazaoSocial;
    private javax.swing.JTextField txtAgendarPagamento_VisualizarConta_Situacao;
    // End of variables declaration//GEN-END:variables
}
