/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Fornecedor;
import controller.Pessoa;


import org.hibernate.Session;
import org.hibernate.Query;

import javax.swing.table.DefaultTableModel;
import java.util.Iterator;
import java.util.Locale;
import javax.swing.JOptionPane;

/**
 *
 * @author Urbanski
 */
public class IFrmAgendarPagamento_SelecionarFornecedor extends javax.swing.JInternalFrame {

    /**
     * Creates new form ifrmAgendarPagamento_AdicionarFornecedor
     */
    DefaultTableModel dtmFornecedor;
    int id;
    Fornecedor f = new Fornecedor();
    
    private void carregaTabela(){
        dtmFornecedor = (DefaultTableModel)tblAgendarPagamento_AdicionarFornecedor_Fornecedor.getModel();
        dtmFornecedor.setNumRows(0);
        Fornecedor fTable = new Fornecedor();
        
        Iterator i = fTable.retornaFornecedores(null, 0);
        while(i.hasNext()){
            fTable = (Fornecedor)i.next();
            dtmFornecedor.addRow(fTable.getFornecedor());
        }
    }
    
    public IFrmAgendarPagamento_SelecionarFornecedor(Fornecedor f) {
        initComponents();
        carregaTabela();
        this.f = f;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel21 = new javax.swing.JPanel();
        txtAgendarPagamento_AdicionarFornecedor_Pesquisa = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jScrollPane11 = new javax.swing.JScrollPane();
        tblAgendarPagamento_AdicionarFornecedor_Fornecedor = new javax.swing.JTable();
        jLabel39 = new javax.swing.JLabel();
        cmbAgendarPagamento_Fornecedor_Filtro = new javax.swing.JComboBox<>();
        btnAgendarPagamento_Fornecedor_Selecionar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Selecionar Fornecedor");

        jPanel21.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Selecionar um Fornecedor"));

        jLabel38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/014-search-1.png"))); // NOI18N
        jLabel38.setText("Pesquisar");

        tblAgendarPagamento_AdicionarFornecedor_Fornecedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "RAZÃO SOCIAL", "NOME FANTASIA", "CNPJ", "TEL. FIXO", "E-MAIL"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane11.setViewportView(tblAgendarPagamento_AdicionarFornecedor_Fornecedor);

        jLabel39.setText("Pesquisar por");

        btnAgendarPagamento_Fornecedor_Selecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/png/001-checked.png"))); // NOI18N
        btnAgendarPagamento_Fornecedor_Selecionar.setText("Selecionar Fornecedor");
        btnAgendarPagamento_Fornecedor_Selecionar.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnAgendarPagamento_Fornecedor_Selecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgendarPagamento_Fornecedor_SelecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane11, javax.swing.GroupLayout.DEFAULT_SIZE, 744, Short.MAX_VALUE)
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtAgendarPagamento_AdicionarFornecedor_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel39)
                        .addGap(18, 18, 18)
                        .addComponent(cmbAgendarPagamento_Fornecedor_Filtro, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAgendarPagamento_Fornecedor_Selecionar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAgendarPagamento_AdicionarFornecedor_Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38)
                    .addComponent(cmbAgendarPagamento_Fornecedor_Filtro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jScrollPane11, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgendarPagamento_Fornecedor_Selecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgendarPagamento_Fornecedor_SelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgendarPagamento_Fornecedor_SelecionarActionPerformed
        int linha = tblAgendarPagamento_AdicionarFornecedor_Fornecedor.getSelectedRow();
        
        if(linha >=0){
                id = Integer.valueOf(dtmFornecedor.getValueAt(linha, 0).toString());
                f.setFornecedorId(id);
                IFrmFinanceiro.atualizaAgendarPagamento_Fornecedor();
                dispose();
        }else{
            JOptionPane.showMessageDialog(this, "Seleciona um fornecedor.","ATENÇÃO",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAgendarPagamento_Fornecedor_SelecionarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgendarPagamento_Fornecedor_Selecionar;
    private javax.swing.JComboBox<String> cmbAgendarPagamento_Fornecedor_Filtro;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JTable tblAgendarPagamento_AdicionarFornecedor_Fornecedor;
    private javax.swing.JTextField txtAgendarPagamento_AdicionarFornecedor_Pesquisa;
    // End of variables declaration//GEN-END:variables
}
