package controller;
// Generated 04/10/2017 16:18:01 by Hibernate Tools 4.3.1

import dao.DAOSistema;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import org.hibernate.Query;
import org.hibernate.Session;

/**
 * Acesso generated by hbm2java
 */
public class Acesso  implements java.io.Serializable {


     private Integer acessoId;
     private Usuario usuario;
     private Date dataInicio;
     private Date dataFim;
     private SimpleDateFormat formatoBanco = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

     public String[] getAcesso(){
        return new String[]{
            String.valueOf(this.acessoId),
            String.valueOf(this.dataInicio),
            String.valueOf(this.dataFim)
        };
     }

    public Acesso() {
    }

	
    public Acesso(Usuario usuario, Date dataInicio) {
        this.usuario = usuario;
        this.dataInicio = dataInicio;
    }
    public Acesso(Usuario usuario, Date dataInicio, Date dataFim) {
       this.usuario = usuario;
       this.dataInicio = dataInicio;
       this.dataFim = dataFim;
    }
   
    public Integer getAcessoId() {
        return this.acessoId;
    }
    
    public void setAcessoId(Integer acessoId) {
        this.acessoId = acessoId;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Date getDataInicio() {
        return this.dataInicio;
    }
    
    public void setDataInicio(Date dataInicio) {
        this.dataInicio = dataInicio;
    }
    public Date getDataFim() {
        return this.dataFim;
    }
    
    public void setDataFim(Date dataFim) {
        this.dataFim = dataFim;
    }

    public void iniciaAcesso(Acesso acesso){
        try{
            Session s = DAOSistema.getSessionFactory().openSession();
            s.beginTransaction();
            s.save(acesso);
            s.getTransaction().commit();
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    
    public void finalizaAcesso(Acesso acesso){
        //String sql = "UPDATE Acesso SET dataFim = '"+formatoBanco.format(acesso.getDataFim())+"' WHERE acessoId = '"+acesso.getAcessoId()+"'";
        /*Acesso ac = new Acesso(acesso.getUsuario(), acesso.getDataInicio());
        ac.setAcessoId(acesso.getAcessoId());
        ac.setDataFim(acesso.getDataFim());*/
        try{
            Session s = DAOSistema.getSessionFactory().getCurrentSession();
            s.beginTransaction();
            s.merge(acesso);
            s.getTransaction().commit();
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    
    public int retornaIdUltimoAcesso(){
        String sql = "from Acesso order by acessoId desc";
        try{
            Session s = DAOSistema.getSessionFactory().openSession();
            s.beginTransaction();
            Query q = s.createSQLQuery(sql);
            List l = q.list();
            Iterator i = l.iterator();
            s.getTransaction().commit();
            
            Acesso a;
            if(i.hasNext()){
               a = (Acesso)i.next();
               return a.getAcessoId()-1; 
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
        return -1;
    }
    
    public Acesso retornaUltimoAcesso(int ultAcessoId){
        String sql = "from Acesso where acessoId = '"+ultAcessoId+"'";
        try{
            Session s = DAOSistema.getSessionFactory().openSession();
            s.beginTransaction();
            Query q = s.createQuery(sql);
            List l = q.list();
            Iterator i = l.iterator();
            s.getTransaction().commit();
            
            Acesso a;
            if(i.hasNext()){
                a = (Acesso)i.next();
                return a;
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
        return null;
    }


}


