package controller;
// Generated 04/10/2017 16:18:01 by Hibernate Tools 4.3.1

import dao.DAOSistema;

import org.hibernate.Query;
import org.hibernate.Session;

import java.util.List;
import java.util.Iterator;

import java.util.HashSet;
import java.util.Set;

/**
 * Cidade generated by hbm2java
 */
public class Cidade  implements java.io.Serializable {


     private Integer cidadeId;
     private Estado estado;
     private String nome;
     private Set enderecos = new HashSet(0);
    
     public String[] getCidade(){
         return new String[] {
           String.valueOf(this.cidadeId),
             nome.toUpperCase()
         };
     }
    public Cidade() {
    }

	
    public Cidade(Estado estado, String nome) {
        this.estado = estado;
        this.nome = nome;
    }
    public Cidade(Estado estado, String nome, Set enderecos) {
       this.estado = estado;
       this.nome = nome;
       this.enderecos = enderecos;
    }
   
    public Integer getCidadeId() {
        return this.cidadeId;
    }
    
    public void setCidadeId(Integer cidadeId) {
        this.cidadeId = cidadeId;
    }
    public Estado getEstado() {
        return this.estado;
    }
    
    public void setEstado(Estado estado) {
        this.estado = estado;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public Set getEnderecos() {
        return this.enderecos;
    }
    
    public void setEnderecos(Set enderecos) {
        this.enderecos = enderecos;
    }

    public Iterator carregaCidades(int estadoId){
        //String sql = "from Cidade c inner join fetch c.estado as e where e.estadoId ='"+estadoId+"' order by c.nome";
        String sql = "from Cidade c where c.estado.estadoId='"+estadoId+"'";
        try{
            Session s = DAOSistema.getSessionFactory().openSession();
            s.beginTransaction();
            Query q = s.createQuery(sql);
            List lForm = q.list();
            Iterator i = lForm.iterator();
            s.getTransaction().commit();
            return i;
        }catch(Exception ex ){
            ex.printStackTrace();
        }
        return null;
    }
    
     public Iterator carregaCidade(String nome,String uf){
        String sql = "from Cidade where nome = '"+nome+"' and estado.uf = '"+uf+"'";
        
        try{
            Session s = DAOSistema.getSessionFactory().getCurrentSession();
            s.beginTransaction();
            Query q = s.createQuery(sql);
            List l = q.list();
            Iterator i = l.iterator();
            s.getTransaction().commit();
            return i;
        }catch(Exception  ex){
            ex.printStackTrace();
        }
        return null;
    }
}


