package controller;
// Generated 04/10/2017 16:18:01 by Hibernate Tools 4.3.1

import dao.DAOSistema;
import java.util.Iterator;
import java.util.List;
import org.hibernate.Query;
import org.hibernate.Session;




/**
 * Endereco generated by hbm2java
 */
public class Endereco implements java.io.Serializable {


     private Integer enderecoId;
     private Cidade cidade;
     private Pessoa pessoa;
     private String rua;
     private int numero;
     private String bairro;
     private String cep;

     public String[] getEndereco(){
         return new String[]{
           String.valueOf(enderecoId),
             String.valueOf(this.pessoa.getPessoaId()),
             this.rua.toUpperCase(),
             String.valueOf(this.numero),
             bairro.toUpperCase(),
             cep
         };
     }
    public Endereco() {
    }

    public Endereco(Pessoa pessoa,Cidade cidade,String rua, int numero, String bairro, String cep) {
       this.pessoa = pessoa;
       this.cidade = cidade;
       this.rua = rua.toUpperCase();
       this.numero = numero;
       this.bairro = bairro.toUpperCase();
       this.cep = cep;
    }
   
    public Integer getEnderecoId() {
        return this.enderecoId;
    }
    
    public void setEnderecoId(Integer enderecoId) {
        this.enderecoId = enderecoId;
    }
    public Cidade getCidade() {
        return this.cidade;
    }
    
    public void setCidade(Cidade cidade) {
        this.cidade = cidade;
    }
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public String getRua() {
        return this.rua;
    }
    
    public void setRua(String rua) {
        this.rua = rua;
    }
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }

    public void cadastraEndereco(Endereco endereco){
        try{
           Session s = DAOSistema.getSessionFactory().openSession();
           s.beginTransaction();
           s.save(endereco);
           s.getTransaction().commit();
       }catch(Exception ex){
           ex.printStackTrace();
       }
    }
    
     public Endereco retornaEndereco(int pessoaId){
        String sql = "from Endereco where pessoa.pessoaId = '"+pessoaId+"'";
        try{
            Session s = DAOSistema.getSessionFactory().openSession();
            s.beginTransaction();
            Query q = s.createQuery(sql);
            List l = q.list();
            Iterator i = l.iterator();
            s.getTransaction().commit();
            Endereco e;
            if(i.hasNext()){
               e = (Endereco)i.next();
               return e;
            }
        }catch(Exception ex){
            ex.printStackTrace();
        }
        return null;
    }

    public void excluirEndereco(Endereco e){
        String sql = "delete Endereco where enderecoId = '"+e.getEnderecoId()+"'";
        try{
            Session s = DAOSistema.getSessionFactory().openSession();
            s.beginTransaction();
            Query q = s.createQuery(sql);
            q.executeUpdate();
            s.getTransaction().commit();
        }catch(Exception ex){
            ex.printStackTrace();
        }
        
    }

}


