package controller;
// Generated 04/10/2017 16:18:01 by Hibernate Tools 4.3.1


import dao.DAOSistema;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import org.hibernate.Query;
import org.hibernate.Session;

/**
 * Estado generated by hbm2java
 */
public class Estado  implements java.io.Serializable {


     private Integer estadoId;
     private String nome;
     private String uf;
     private Set cidades = new HashSet(0);

     public String[] getEstado(){
         return new String[]{
           String.valueOf(estadoId),
             nome,
             uf
         };
     }
    public Estado() {
    }

	
    public Estado(String nome, String uf) {
        this.nome = nome;
        this.uf = uf;
    }
    public Estado(String nome, String uf, Set cidades) {
       this.nome = nome;
       this.uf = uf;
       this.cidades = cidades;
    }
   
    public Integer getEstadoId() {
        return this.estadoId;
    }
    
    public void setEstadoId(Integer estadoId) {
        this.estadoId = estadoId;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getUf() {
        return this.uf;
    }
    
    public void setUf(String uf) {
        this.uf = uf;
    }
    public Set getCidades() {
        return this.cidades;
    }
    
    public void setCidades(Set cidades) {
        this.cidades = cidades;
    }
    public Iterator carregaEstados(){
     String sql = "from Estado order by uf";
        
        try{
            Session s = DAOSistema.getSessionFactory().getCurrentSession();
            s.beginTransaction();
            Query q = s.createQuery(sql);
            List lForm = q.list();
            Iterator i = lForm.iterator();
            s.getTransaction().commit();
            return i;
        }catch(Exception ex){
            ex.printStackTrace();
        }
        return null;
    }
    
    public Iterator buscaEstado(String sigla){
        String sql = "from Estado as e where e.uf='"+sigla+"'";
        
        try{            
            Session s = DAOSistema.getSessionFactory().openSession();
            s.beginTransaction();
            Query q = s.createQuery(sql);
            List l = q.list();
            Iterator i = l.iterator();
            s.getTransaction().commit();
            return i;
        }catch(Exception ex){
            ex.printStackTrace();
        }
        return null;
    }
    
    
}


