package controller;
// Generated 04/10/2017 16:18:01 by Hibernate Tools 4.3.1

import dao.DAOSistema;
import org.hibernate.Session;
import org.hibernate.Query;
import java.util.List;
import java.util.Iterator;
import java.util.Date;

/**
 * Movimento generated by hbm2java
 */
public class Movimento  implements java.io.Serializable {


     private Integer movimentoId;
     private Caixa caixa;
     private Tipomovimento tipomovimento;
     private String descricao;
     private double valor;
     private Date data;

     public String[] getMovimento(){
         return new String[]{
             String.valueOf(this.movimentoId),
             this.descricao,
             String.valueOf(this.valor),
             String.valueOf(this.data)
         };
     }
    public Movimento() {
    }

    public Movimento(Caixa caixa, Tipomovimento tipomovimento, String descricao, double valor) {
       this.caixa = caixa;
       this.tipomovimento = tipomovimento;
       this.descricao = descricao;
       this.valor = valor;
    }
   
    public Integer getMovimentoId() {
        return this.movimentoId;
    }
    
    public void setMovimentoId(Integer movimentoId) {
        this.movimentoId = movimentoId;
    }
    public Caixa getCaixa() {
        return this.caixa;
    }
    
    public void setCaixa(Caixa caixa) {
        this.caixa = caixa;
    }
    public Tipomovimento getTipomovimento() {
        return this.tipomovimento;
    }
    
    public void setTipomovimento(Tipomovimento tipomovimento) {
        this.tipomovimento = tipomovimento;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public double getValor() {
        return this.valor;
    }
    
    public void setValor(double valor) {
        this.valor = valor;
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }

    
    public void cadastraMovimento(Movimento movimento){
        try{
            Session s = DAOSistema.getSessionFactory().openSession();
            s.beginTransaction();
            s.save(movimento);
            s.getTransaction().commit();
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }


}


