package controller;
// Generated 04/10/2017 16:18:01 by Hibernate Tools 4.3.1


import dao.DAOSistema;


import java.util.HashSet;
import java.util.Iterator;
import java.util.List;
import java.util.Set;
import org.hibernate.Session;
import org.hibernate.Query;

/**
 * Nivelacesso generated by hbm2java
 */
public class Nivelacesso  implements java.io.Serializable {


     private Integer nivelAcessoId;
     private Integer nivel;
     private String descricao;
     private Set usuarios = new HashSet(0);

     public String[] getNivelAcesso(){
         return new String[]{
           String.valueOf(this.nivelAcessoId),
             String.valueOf(this.nivel),
             this.descricao
         };
     }
    public Nivelacesso() {
    }

    public Nivelacesso(Integer nivel, String descricao, Set usuarios) {
       this.nivel = nivel;
       this.descricao = descricao;
       this.usuarios = usuarios;
    }
   
    public Integer getNivelAcessoId() {
        return this.nivelAcessoId;
    }
    
    public void setNivelAcessoId(Integer nivelAcessoId) {
        this.nivelAcessoId = nivelAcessoId;
    }
    public Integer getNivel() {
        return this.nivel;
    }
    
    public void setNivel(Integer nivel) {
        this.nivel = nivel;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }

    public Iterator retornaNivelAcesso(){
        String sql = "from Nivelacesso";
        try{
            Session s = DAOSistema.getSessionFactory().getCurrentSession();
            s.beginTransaction();
            Query q = s.createQuery(sql);
            List l = q.list();
            Iterator i = l.iterator();
            s.getTransaction().commit();
            return i;
        }catch(Exception ex){
            ex.printStackTrace();
        }
        return null;
    }
    
    public Iterator retornaNivelAcesso(int nivel){
        String sql = "from Nivelacesso where nivel ='"+nivel+"'";
        try{
            Session s = DAOSistema.getSessionFactory().getCurrentSession();
            s.beginTransaction();
            Query q = s.createQuery(sql);
            List l = q.list();
            Iterator i = l.iterator();
            s.getTransaction().commit();
            return i;
        }catch(Exception ex){
            ex.printStackTrace();
        }
        return null;
    }


}


