package controller;
// Generated 04/10/2017 16:18:01 by Hibernate Tools 4.3.1


import dao.DAOSistema;
import java.util.HashSet;
import java.util.Set;
import org.hibernate.Query;
import org.hibernate.Session;

/**
 * Pessoa generated by hbm2java
 */
public class Pessoa  implements java.io.Serializable {


     private Integer pessoaId;
     private String nome;
     private String email;
     private String telFixo;
     private String telCel;
     private Set fornecedors = new HashSet(0);
     private Set usuarios = new HashSet(0);
     private Set enderecos = new HashSet(0);

     public String[] getPessoa(){
         return new String[]{
           String.valueOf(this.pessoaId),
             this.nome.toUpperCase(),
             this.email,
             this.telFixo,
             this.telCel
         };
     }
     
    public Pessoa() {
    }

	
    public Pessoa(String nome, String email, String telFixo, String telCel) {
        this.nome = nome.toUpperCase();
        this.email = email;
        this.telFixo = telFixo;
        this.telCel = telCel;
    }
    public Pessoa(String nome, String email, String telFixo, String telCel, Set fornecedors, Set usuarios, Set enderecos) {
       this.nome = nome.toUpperCase();
       this.email = email;
       this.telFixo = telFixo.toUpperCase();
       this.telCel = telCel.toUpperCase();
       this.fornecedors = fornecedors;
       this.usuarios = usuarios;
       this.enderecos = enderecos;
    }
   
    
    public Integer getPessoaId() {
        return this.pessoaId;
    }
    
    public void setPessoaId(Integer pessoaId) {
        this.pessoaId = pessoaId;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelFixo() {
        return this.telFixo;
    }
    
    public void setTelFixo(String telFixo) {
        this.telFixo = telFixo;
    }
    public String getTelCel() {
        return this.telCel;
    }
    
    public void setTelCel(String telCel) {
        this.telCel = telCel;
    }
    public Set getFornecedors() {
        return this.fornecedors;
    }
    
    public void setFornecedors(Set fornecedors) {
        this.fornecedors = fornecedors;
    }
    public Set getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set usuarios) {
        this.usuarios = usuarios;
    }
    public Set getEnderecos() {
        return this.enderecos;
    }
    
    public void setEnderecos(Set enderecos) {
        this.enderecos = enderecos;
    }
    
    public void cadastraPessoa(Pessoa pessoa){
         try{
            Session s = DAOSistema.getSessionFactory().openSession();
            s.beginTransaction();
            s.save(pessoa);
            s.getTransaction().commit();
        }catch(Exception ex ){
            ex.printStackTrace();
        }
    }
    
    public void excluirPessoa(Pessoa p){
        String sql = "delete Pessoa where pessoaId = '"+p.getPessoaId()+"'";
        try{
            Session s = DAOSistema.getSessionFactory().openSession();
            s.beginTransaction();
            Query q = s.createQuery(sql);
            q.executeUpdate();
            s.getTransaction().commit();
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    
    public void alteraPessoa(Pessoa p){
        try{
            Session s = DAOSistema.getSessionFactory().openSession();
            s.beginTransaction();
            s.merge(p);
            s.getTransaction().commit();
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }
    


}


