package controller;
// Generated 04/10/2017 16:18:01 by Hibernate Tools 4.3.1

import dao.DAOSistema;

import org.hibernate.Session;
import org.hibernate.Query;

import java.util.Set;
import java.util.HashSet;
import java.util.Iterator;
import java.util.List;


/**
 * Situacao generated by hbm2java
 */
public class Situacao  implements java.io.Serializable {


     private Integer situacaoId;
     private String status;
     private String descricao;
     private Set transacaos = new HashSet(0);
     private Set chamados = new HashSet(0);

     public String[] getSituacao(){
         return new String[]{
           String.valueOf(this.situacaoId),
             this.status,
             this.descricao
         };
     }
    public Situacao() {
    }
    
	
    public Situacao(String status, String descricao) {
        this.status = status;
        this.descricao = descricao;
    }
    public Situacao(String status, String descricao, Set transacaos, Set chamados) {
       this.status = status;
       this.descricao = descricao;
       this.transacaos = transacaos;
       this.chamados = chamados;
    }
   
    public Integer getSituacaoId() {
        return this.situacaoId;
    }
    
    public void setSituacaoId(Integer situacaoId) {
        this.situacaoId = situacaoId;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getTransacaos() {
        return this.transacaos;
    }
    
    public void setTransacaos(Set transacaos) {
        this.transacaos = transacaos;
    }
    public Set getChamados() {
        return this.chamados;
    }
    
    public void setChamados(Set chamados) {
        this.chamados = chamados;
    }

    public Situacao retornaSituacao(int situacaoId){
        String sql = "from Situacao where situacaoId='"+situacaoId+"'";
        
        try{
            Session s = DAOSistema.getSessionFactory().openSession();
            s.beginTransaction();
            Query q = s.createQuery(sql);
            List l = q.list();
            Iterator i = l.iterator();
            Situacao situacao;
            if(i.hasNext()){
                situacao = (Situacao)i.next();
                return situacao;
            }
            s.getTransaction().commit();
            
        }catch(Exception ex){
            ex.printStackTrace();
        }
        return null;
    }

   

}


