package controller;
// Generated 04/10/2017 16:18:01 by Hibernate Tools 4.3.1

import dao.DAOSistema;
import org.hibernate.Session;
import org.hibernate.Query;

import java.util.List;
import java.util.Iterator;
import java.util.HashSet;
import java.util.Set;
import org.hibernate.Session;

/**
 * Tipomovimento generated by hbm2java
 */
public class Tipomovimento  implements java.io.Serializable {


     private Integer tipoMovimentoId;
     private String tipo;
     private String descricao;
     private Set movimentos = new HashSet(0);

     public String[] getTipoMovimento(){
         return new String[]{
           String.valueOf(this.tipoMovimentoId),
             this.tipo,
             this.descricao
         };
     }
    public Tipomovimento() {
    }

	
    public Tipomovimento(String tipo, String descricao) {
        this.tipo = tipo;
        this.descricao = descricao;
    }
    public Tipomovimento(String tipo, String descricao, Set movimentos) {
       this.tipo = tipo;
       this.descricao = descricao;
       this.movimentos = movimentos;
    }
   
    public Integer getTipoMovimentoId() {
        return this.tipoMovimentoId;
    }
    
    public void setTipoMovimentoId(Integer tipoMovimentoId) {
        this.tipoMovimentoId = tipoMovimentoId;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getMovimentos() {
        return this.movimentos;
    }
    
    public void setMovimentos(Set movimentos) {
        this.movimentos = movimentos;
    }

    public Tipomovimento retornaTipoMovimento(int tipoMovimentoId){
        String sql = "from Tipomovimento where tipoMovimentoId = '"+tipoMovimentoId+"'";
        try{
            Session s = DAOSistema.getSessionFactory().openSession();
            s.beginTransaction();
            Query q = s.createQuery(sql);
            List l = q.list();
            Iterator i = l.iterator();
            
            Tipomovimento tp;
            
            if(i.hasNext()){
                tp = (Tipomovimento)i.next();
                return tp;
            }
            
        }catch(Exception ex){
            ex.printStackTrace();
        }
        return null;
    }


}


