package controller;
// Generated 04/10/2017 16:18:01 by Hibernate Tools 4.3.1

import dao.DAOSistema;
import controller.Situacao;

import org.hibernate.Session;
import org.hibernate.Query;

import java.util.List;
import java.util.Iterator;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Transacao generated by hbm2java
 */
public class Transacao  implements java.io.Serializable {


     private Integer transacaoId;
     private Situacao situacao;
     private Date data;
     private String descricao;
     private Set contarecebers = new HashSet(0);
     private Set contapagars = new HashSet(0);

     public String[] getTransacao(){
         return new String[]{
           String.valueOf(this.transacaoId),
             String.valueOf(this.data),
             this.descricao
         };
     }
    public Transacao() {
    }

	
    public Transacao(Situacao situacao, String descricao) {
        this.situacao = situacao;
        this.descricao = descricao;
    }
    public Transacao(Situacao situacao, String descricao, Set contarecebers, Set contapagars) {
       this.situacao = situacao;
       this.descricao = descricao;
       this.contarecebers = contarecebers;
       this.contapagars = contapagars;
    }
   
    public Integer getTransacaoId() {
        return this.transacaoId;
    }
    
    public void setTransacaoId(Integer transacaoId) {
        this.transacaoId = transacaoId;
    }
    public Situacao getSituacao() {
        return this.situacao;
    }
    
    public void setSituacao(Situacao situacao) {
        this.situacao = situacao;
    }
    public void setSituacaoId(int situacaoId){
        this.situacao.setSituacaoId(situacaoId);
    }
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    public Set getContarecebers() {
        return this.contarecebers;
    }
    
    public void setContarecebers(Set contarecebers) {
        this.contarecebers = contarecebers;
    }
    public Set getContapagars() {
        return this.contapagars;
    }
    
    public void setContapagars(Set contapagars) {
        this.contapagars = contapagars;
    }
    
    public void cadastraTransacao(Transacao transacao){
        try{
            Session s = DAOSistema.getSessionFactory().openSession();
            s.beginTransaction();
            s.save(transacao);
            s.getTransaction().commit();
        }catch(Exception ex){
            ex.printStackTrace();
        }
    }



}


